/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Apiv1crcordersBraintreeBraintreeFraudIndicators
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
public class Apiv1crcordersBraintreeBraintreeFraudIndicators {
  @SerializedName("CvvResponseCode")
  private String cvvResponseCode = null;

  @SerializedName("AvsStreetAddressResponseCode")
  private String avsStreetAddressResponseCode = null;

  @SerializedName("AvsPostalCodeResponseCode")
  private String avsPostalCodeResponseCode = null;

  @SerializedName("AvsErrorResponseCode")
  private String avsErrorResponseCode = null;

  public Apiv1crcordersBraintreeBraintreeFraudIndicators cvvResponseCode(String cvvResponseCode) {
    this.cvvResponseCode = cvvResponseCode;
    return this;
  }

   /**
   * Get cvvResponseCode
   * @return cvvResponseCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCvvResponseCode() {
    return cvvResponseCode;
  }

  public void setCvvResponseCode(String cvvResponseCode) {
    this.cvvResponseCode = cvvResponseCode;
  }

  public Apiv1crcordersBraintreeBraintreeFraudIndicators avsStreetAddressResponseCode(String avsStreetAddressResponseCode) {
    this.avsStreetAddressResponseCode = avsStreetAddressResponseCode;
    return this;
  }

   /**
   * Get avsStreetAddressResponseCode
   * @return avsStreetAddressResponseCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAvsStreetAddressResponseCode() {
    return avsStreetAddressResponseCode;
  }

  public void setAvsStreetAddressResponseCode(String avsStreetAddressResponseCode) {
    this.avsStreetAddressResponseCode = avsStreetAddressResponseCode;
  }

  public Apiv1crcordersBraintreeBraintreeFraudIndicators avsPostalCodeResponseCode(String avsPostalCodeResponseCode) {
    this.avsPostalCodeResponseCode = avsPostalCodeResponseCode;
    return this;
  }

   /**
   * Get avsPostalCodeResponseCode
   * @return avsPostalCodeResponseCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAvsPostalCodeResponseCode() {
    return avsPostalCodeResponseCode;
  }

  public void setAvsPostalCodeResponseCode(String avsPostalCodeResponseCode) {
    this.avsPostalCodeResponseCode = avsPostalCodeResponseCode;
  }

  public Apiv1crcordersBraintreeBraintreeFraudIndicators avsErrorResponseCode(String avsErrorResponseCode) {
    this.avsErrorResponseCode = avsErrorResponseCode;
    return this;
  }

   /**
   * Get avsErrorResponseCode
   * @return avsErrorResponseCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAvsErrorResponseCode() {
    return avsErrorResponseCode;
  }

  public void setAvsErrorResponseCode(String avsErrorResponseCode) {
    this.avsErrorResponseCode = avsErrorResponseCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv1crcordersBraintreeBraintreeFraudIndicators apiv1crcordersBraintreeBraintreeFraudIndicators = (Apiv1crcordersBraintreeBraintreeFraudIndicators) o;
    return Objects.equals(this.cvvResponseCode, apiv1crcordersBraintreeBraintreeFraudIndicators.cvvResponseCode) &&
        Objects.equals(this.avsStreetAddressResponseCode, apiv1crcordersBraintreeBraintreeFraudIndicators.avsStreetAddressResponseCode) &&
        Objects.equals(this.avsPostalCodeResponseCode, apiv1crcordersBraintreeBraintreeFraudIndicators.avsPostalCodeResponseCode) &&
        Objects.equals(this.avsErrorResponseCode, apiv1crcordersBraintreeBraintreeFraudIndicators.avsErrorResponseCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cvvResponseCode, avsStreetAddressResponseCode, avsPostalCodeResponseCode, avsErrorResponseCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv1crcordersBraintreeBraintreeFraudIndicators {\n");
    
    sb.append("    cvvResponseCode: ").append(toIndentedString(cvvResponseCode)).append("\n");
    sb.append("    avsStreetAddressResponseCode: ").append(toIndentedString(avsStreetAddressResponseCode)).append("\n");
    sb.append("    avsPostalCodeResponseCode: ").append(toIndentedString(avsPostalCodeResponseCode)).append("\n");
    sb.append("    avsErrorResponseCode: ").append(toIndentedString(avsErrorResponseCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

