/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Apiv1crcordersItemPromotions;
import io.swagger.client.model.Apiv1crcordersKitItems;
import java.util.ArrayList;
import java.util.List;

/**
 * Apiv1crcordersItems
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
public class Apiv1crcordersItems {
  @SerializedName("ReferenceSKU")
  private String referenceSKU = null;

  @SerializedName("Status")
  private String status = null;

  @SerializedName("ItemPromotions")
  private List<Apiv1crcordersItemPromotions> itemPromotions = new ArrayList<Apiv1crcordersItemPromotions>();

  @SerializedName("IsKit")
  private String isKit = null;

  @SerializedName("KitType")
  private String kitType = null;

  @SerializedName("KitItems")
  private List<Apiv1crcordersKitItems> kitItems = new ArrayList<Apiv1crcordersKitItems>();

  @SerializedName("ReferenceLineId")
  private String referenceLineId = null;

  @SerializedName("GroupStockId")
  private String groupStockId = null;

  @SerializedName("Quantity")
  private Integer quantity = null;

  @SerializedName("UnitPrice")
  private Double unitPrice = null;

  @SerializedName("TotalPrice")
  private Double totalPrice = null;

  @SerializedName("PriceBeforeDiscount")
  private Double priceBeforeDiscount = null;

  @SerializedName("UnitCostExVAT")
  private Double unitCostExVAT = null;

  @SerializedName("CountryVATRate")
  private Double countryVATRate = null;

  @SerializedName("UnitVATAmt")
  private Double unitVATAmt = null;

  @SerializedName("TotalItemCostExVAT")
  private Double totalItemCostExVAT = null;

  @SerializedName("TotalItemVAT")
  private Double totalItemVAT = null;

  public Apiv1crcordersItems referenceSKU(String referenceSKU) {
    this.referenceSKU = referenceSKU;
    return this;
  }

   /**
   * Get referenceSKU
   * @return referenceSKU
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReferenceSKU() {
    return referenceSKU;
  }

  public void setReferenceSKU(String referenceSKU) {
    this.referenceSKU = referenceSKU;
  }

  public Apiv1crcordersItems status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Apiv1crcordersItems itemPromotions(List<Apiv1crcordersItemPromotions> itemPromotions) {
    this.itemPromotions = itemPromotions;
    return this;
  }

  public Apiv1crcordersItems addItemPromotionsItem(Apiv1crcordersItemPromotions itemPromotionsItem) {
    this.itemPromotions.add(itemPromotionsItem);
    return this;
  }

   /**
   * Get itemPromotions
   * @return itemPromotions
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Apiv1crcordersItemPromotions> getItemPromotions() {
    return itemPromotions;
  }

  public void setItemPromotions(List<Apiv1crcordersItemPromotions> itemPromotions) {
    this.itemPromotions = itemPromotions;
  }

  public Apiv1crcordersItems isKit(String isKit) {
    this.isKit = isKit;
    return this;
  }

   /**
   * Get isKit
   * @return isKit
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIsKit() {
    return isKit;
  }

  public void setIsKit(String isKit) {
    this.isKit = isKit;
  }

  public Apiv1crcordersItems kitType(String kitType) {
    this.kitType = kitType;
    return this;
  }

   /**
   * Get kitType
   * @return kitType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getKitType() {
    return kitType;
  }

  public void setKitType(String kitType) {
    this.kitType = kitType;
  }

  public Apiv1crcordersItems kitItems(List<Apiv1crcordersKitItems> kitItems) {
    this.kitItems = kitItems;
    return this;
  }

  public Apiv1crcordersItems addKitItemsItem(Apiv1crcordersKitItems kitItemsItem) {
    this.kitItems.add(kitItemsItem);
    return this;
  }

   /**
   * Get kitItems
   * @return kitItems
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Apiv1crcordersKitItems> getKitItems() {
    return kitItems;
  }

  public void setKitItems(List<Apiv1crcordersKitItems> kitItems) {
    this.kitItems = kitItems;
  }

  public Apiv1crcordersItems referenceLineId(String referenceLineId) {
    this.referenceLineId = referenceLineId;
    return this;
  }

   /**
   * Get referenceLineId
   * @return referenceLineId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReferenceLineId() {
    return referenceLineId;
  }

  public void setReferenceLineId(String referenceLineId) {
    this.referenceLineId = referenceLineId;
  }

  public Apiv1crcordersItems groupStockId(String groupStockId) {
    this.groupStockId = groupStockId;
    return this;
  }

   /**
   * Get groupStockId
   * @return groupStockId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGroupStockId() {
    return groupStockId;
  }

  public void setGroupStockId(String groupStockId) {
    this.groupStockId = groupStockId;
  }

  public Apiv1crcordersItems quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public Apiv1crcordersItems unitPrice(Double unitPrice) {
    this.unitPrice = unitPrice;
    return this;
  }

   /**
   * Get unitPrice
   * @return unitPrice
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getUnitPrice() {
    return unitPrice;
  }

  public void setUnitPrice(Double unitPrice) {
    this.unitPrice = unitPrice;
  }

  public Apiv1crcordersItems totalPrice(Double totalPrice) {
    this.totalPrice = totalPrice;
    return this;
  }

   /**
   * Get totalPrice
   * @return totalPrice
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getTotalPrice() {
    return totalPrice;
  }

  public void setTotalPrice(Double totalPrice) {
    this.totalPrice = totalPrice;
  }

  public Apiv1crcordersItems priceBeforeDiscount(Double priceBeforeDiscount) {
    this.priceBeforeDiscount = priceBeforeDiscount;
    return this;
  }

   /**
   * Get priceBeforeDiscount
   * @return priceBeforeDiscount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getPriceBeforeDiscount() {
    return priceBeforeDiscount;
  }

  public void setPriceBeforeDiscount(Double priceBeforeDiscount) {
    this.priceBeforeDiscount = priceBeforeDiscount;
  }

  public Apiv1crcordersItems unitCostExVAT(Double unitCostExVAT) {
    this.unitCostExVAT = unitCostExVAT;
    return this;
  }

   /**
   * Get unitCostExVAT
   * @return unitCostExVAT
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getUnitCostExVAT() {
    return unitCostExVAT;
  }

  public void setUnitCostExVAT(Double unitCostExVAT) {
    this.unitCostExVAT = unitCostExVAT;
  }

  public Apiv1crcordersItems countryVATRate(Double countryVATRate) {
    this.countryVATRate = countryVATRate;
    return this;
  }

   /**
   * Get countryVATRate
   * @return countryVATRate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getCountryVATRate() {
    return countryVATRate;
  }

  public void setCountryVATRate(Double countryVATRate) {
    this.countryVATRate = countryVATRate;
  }

  public Apiv1crcordersItems unitVATAmt(Double unitVATAmt) {
    this.unitVATAmt = unitVATAmt;
    return this;
  }

   /**
   * Get unitVATAmt
   * @return unitVATAmt
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getUnitVATAmt() {
    return unitVATAmt;
  }

  public void setUnitVATAmt(Double unitVATAmt) {
    this.unitVATAmt = unitVATAmt;
  }

  public Apiv1crcordersItems totalItemCostExVAT(Double totalItemCostExVAT) {
    this.totalItemCostExVAT = totalItemCostExVAT;
    return this;
  }

   /**
   * Get totalItemCostExVAT
   * @return totalItemCostExVAT
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getTotalItemCostExVAT() {
    return totalItemCostExVAT;
  }

  public void setTotalItemCostExVAT(Double totalItemCostExVAT) {
    this.totalItemCostExVAT = totalItemCostExVAT;
  }

  public Apiv1crcordersItems totalItemVAT(Double totalItemVAT) {
    this.totalItemVAT = totalItemVAT;
    return this;
  }

   /**
   * Get totalItemVAT
   * @return totalItemVAT
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getTotalItemVAT() {
    return totalItemVAT;
  }

  public void setTotalItemVAT(Double totalItemVAT) {
    this.totalItemVAT = totalItemVAT;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv1crcordersItems apiv1crcordersItems = (Apiv1crcordersItems) o;
    return Objects.equals(this.referenceSKU, apiv1crcordersItems.referenceSKU) &&
        Objects.equals(this.status, apiv1crcordersItems.status) &&
        Objects.equals(this.itemPromotions, apiv1crcordersItems.itemPromotions) &&
        Objects.equals(this.isKit, apiv1crcordersItems.isKit) &&
        Objects.equals(this.kitType, apiv1crcordersItems.kitType) &&
        Objects.equals(this.kitItems, apiv1crcordersItems.kitItems) &&
        Objects.equals(this.referenceLineId, apiv1crcordersItems.referenceLineId) &&
        Objects.equals(this.groupStockId, apiv1crcordersItems.groupStockId) &&
        Objects.equals(this.quantity, apiv1crcordersItems.quantity) &&
        Objects.equals(this.unitPrice, apiv1crcordersItems.unitPrice) &&
        Objects.equals(this.totalPrice, apiv1crcordersItems.totalPrice) &&
        Objects.equals(this.priceBeforeDiscount, apiv1crcordersItems.priceBeforeDiscount) &&
        Objects.equals(this.unitCostExVAT, apiv1crcordersItems.unitCostExVAT) &&
        Objects.equals(this.countryVATRate, apiv1crcordersItems.countryVATRate) &&
        Objects.equals(this.unitVATAmt, apiv1crcordersItems.unitVATAmt) &&
        Objects.equals(this.totalItemCostExVAT, apiv1crcordersItems.totalItemCostExVAT) &&
        Objects.equals(this.totalItemVAT, apiv1crcordersItems.totalItemVAT);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referenceSKU, status, itemPromotions, isKit, kitType, kitItems, referenceLineId, groupStockId, quantity, unitPrice, totalPrice, priceBeforeDiscount, unitCostExVAT, countryVATRate, unitVATAmt, totalItemCostExVAT, totalItemVAT);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv1crcordersItems {\n");
    
    sb.append("    referenceSKU: ").append(toIndentedString(referenceSKU)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    itemPromotions: ").append(toIndentedString(itemPromotions)).append("\n");
    sb.append("    isKit: ").append(toIndentedString(isKit)).append("\n");
    sb.append("    kitType: ").append(toIndentedString(kitType)).append("\n");
    sb.append("    kitItems: ").append(toIndentedString(kitItems)).append("\n");
    sb.append("    referenceLineId: ").append(toIndentedString(referenceLineId)).append("\n");
    sb.append("    groupStockId: ").append(toIndentedString(groupStockId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("    priceBeforeDiscount: ").append(toIndentedString(priceBeforeDiscount)).append("\n");
    sb.append("    unitCostExVAT: ").append(toIndentedString(unitCostExVAT)).append("\n");
    sb.append("    countryVATRate: ").append(toIndentedString(countryVATRate)).append("\n");
    sb.append("    unitVATAmt: ").append(toIndentedString(unitVATAmt)).append("\n");
    sb.append("    totalItemCostExVAT: ").append(toIndentedString(totalItemCostExVAT)).append("\n");
    sb.append("    totalItemVAT: ").append(toIndentedString(totalItemVAT)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

