/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Apiv1crcordersPromotionList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
public class Apiv1crcordersPromotionList {
  @SerializedName("CouponId")
  private String couponId = null;

  @SerializedName("PromotionName")
  private String promotionName = null;

  @SerializedName("PromotionId")
  private String promotionId = null;

  @SerializedName("PromotionType")
  private String promotionType = null;

  @SerializedName("DiscountPrice")
  private Double discountPrice = null;

  public Apiv1crcordersPromotionList couponId(String couponId) {
    this.couponId = couponId;
    return this;
  }

   /**
   * Get couponId
   * @return couponId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCouponId() {
    return couponId;
  }

  public void setCouponId(String couponId) {
    this.couponId = couponId;
  }

  public Apiv1crcordersPromotionList promotionName(String promotionName) {
    this.promotionName = promotionName;
    return this;
  }

   /**
   * Get promotionName
   * @return promotionName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPromotionName() {
    return promotionName;
  }

  public void setPromotionName(String promotionName) {
    this.promotionName = promotionName;
  }

  public Apiv1crcordersPromotionList promotionId(String promotionId) {
    this.promotionId = promotionId;
    return this;
  }

   /**
   * Get promotionId
   * @return promotionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPromotionId() {
    return promotionId;
  }

  public void setPromotionId(String promotionId) {
    this.promotionId = promotionId;
  }

  public Apiv1crcordersPromotionList promotionType(String promotionType) {
    this.promotionType = promotionType;
    return this;
  }

   /**
   * Get promotionType
   * @return promotionType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPromotionType() {
    return promotionType;
  }

  public void setPromotionType(String promotionType) {
    this.promotionType = promotionType;
  }

  public Apiv1crcordersPromotionList discountPrice(Double discountPrice) {
    this.discountPrice = discountPrice;
    return this;
  }

   /**
   * Get discountPrice
   * @return discountPrice
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getDiscountPrice() {
    return discountPrice;
  }

  public void setDiscountPrice(Double discountPrice) {
    this.discountPrice = discountPrice;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Apiv1crcordersPromotionList apiv1crcordersPromotionList = (Apiv1crcordersPromotionList) o;
    return Objects.equals(this.couponId, apiv1crcordersPromotionList.couponId) &&
        Objects.equals(this.promotionName, apiv1crcordersPromotionList.promotionName) &&
        Objects.equals(this.promotionId, apiv1crcordersPromotionList.promotionId) &&
        Objects.equals(this.promotionType, apiv1crcordersPromotionList.promotionType) &&
        Objects.equals(this.discountPrice, apiv1crcordersPromotionList.discountPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(couponId, promotionName, promotionId, promotionType, discountPrice);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Apiv1crcordersPromotionList {\n");
    
    sb.append("    couponId: ").append(toIndentedString(couponId)).append("\n");
    sb.append("    promotionName: ").append(toIndentedString(promotionName)).append("\n");
    sb.append("    promotionId: ").append(toIndentedString(promotionId)).append("\n");
    sb.append("    promotionType: ").append(toIndentedString(promotionType)).append("\n");
    sb.append("    discountPrice: ").append(toIndentedString(discountPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

