/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * InlineResponse2002ItemLocationVirtual
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
public class InlineResponse2002ItemLocationVirtual {
  @SerializedName("ItemId")
  private String itemId = null;

  @SerializedName("LocationId")
  private Long locationId = null;

  @SerializedName("LocationType")
  private String locationType = null;

  @SerializedName("LocalItemDesc")
  private String localItemDesc = null;

  @SerializedName("LocalShortDesc")
  private String localShortDesc = null;

  @SerializedName("Status")
  private String status = null;

  @SerializedName("PrimarySupplierId")
  private Long primarySupplierId = null;

  @SerializedName("PrimaryCountryId")
  private String primaryCountryId = null;

  @SerializedName("ReceiveAsType")
  private String receiveAsType = null;

  @SerializedName("IsItemTaxable")
  private String isItemTaxable = null;

  @SerializedName("SourceMethod")
  private String sourceMethod = null;

  @SerializedName("SourceWarehouse")
  private Long sourceWarehouse = null;

  @SerializedName("UnitRetail")
  private Double unitRetail = null;

  @SerializedName("SellingUnitRetail")
  private Double sellingUnitRetail = null;

  @SerializedName("SellingUom")
  private String sellingUom = null;

  @SerializedName("RangedIndicator")
  private String rangedIndicator = null;

  @SerializedName("Created")
  private DateTime created = null;

  @SerializedName("Modified")
  private DateTime modified = null;

  public InlineResponse2002ItemLocationVirtual itemId(String itemId) {
    this.itemId = itemId;
    return this;
  }

   /**
   * Get itemId
   * @return itemId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getItemId() {
    return itemId;
  }

  public void setItemId(String itemId) {
    this.itemId = itemId;
  }

  public InlineResponse2002ItemLocationVirtual locationId(Long locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Long getLocationId() {
    return locationId;
  }

  public void setLocationId(Long locationId) {
    this.locationId = locationId;
  }

  public InlineResponse2002ItemLocationVirtual locationType(String locationType) {
    this.locationType = locationType;
    return this;
  }

   /**
   * Get locationType
   * @return locationType
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getLocationType() {
    return locationType;
  }

  public void setLocationType(String locationType) {
    this.locationType = locationType;
  }

  public InlineResponse2002ItemLocationVirtual localItemDesc(String localItemDesc) {
    this.localItemDesc = localItemDesc;
    return this;
  }

   /**
   * Get localItemDesc
   * @return localItemDesc
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getLocalItemDesc() {
    return localItemDesc;
  }

  public void setLocalItemDesc(String localItemDesc) {
    this.localItemDesc = localItemDesc;
  }

  public InlineResponse2002ItemLocationVirtual localShortDesc(String localShortDesc) {
    this.localShortDesc = localShortDesc;
    return this;
  }

   /**
   * Get localShortDesc
   * @return localShortDesc
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLocalShortDesc() {
    return localShortDesc;
  }

  public void setLocalShortDesc(String localShortDesc) {
    this.localShortDesc = localShortDesc;
  }

  public InlineResponse2002ItemLocationVirtual status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public InlineResponse2002ItemLocationVirtual primarySupplierId(Long primarySupplierId) {
    this.primarySupplierId = primarySupplierId;
    return this;
  }

   /**
   * Get primarySupplierId
   * @return primarySupplierId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getPrimarySupplierId() {
    return primarySupplierId;
  }

  public void setPrimarySupplierId(Long primarySupplierId) {
    this.primarySupplierId = primarySupplierId;
  }

  public InlineResponse2002ItemLocationVirtual primaryCountryId(String primaryCountryId) {
    this.primaryCountryId = primaryCountryId;
    return this;
  }

   /**
   * Get primaryCountryId
   * @return primaryCountryId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPrimaryCountryId() {
    return primaryCountryId;
  }

  public void setPrimaryCountryId(String primaryCountryId) {
    this.primaryCountryId = primaryCountryId;
  }

  public InlineResponse2002ItemLocationVirtual receiveAsType(String receiveAsType) {
    this.receiveAsType = receiveAsType;
    return this;
  }

   /**
   * Get receiveAsType
   * @return receiveAsType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReceiveAsType() {
    return receiveAsType;
  }

  public void setReceiveAsType(String receiveAsType) {
    this.receiveAsType = receiveAsType;
  }

  public InlineResponse2002ItemLocationVirtual isItemTaxable(String isItemTaxable) {
    this.isItemTaxable = isItemTaxable;
    return this;
  }

   /**
   * Get isItemTaxable
   * @return isItemTaxable
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getIsItemTaxable() {
    return isItemTaxable;
  }

  public void setIsItemTaxable(String isItemTaxable) {
    this.isItemTaxable = isItemTaxable;
  }

  public InlineResponse2002ItemLocationVirtual sourceMethod(String sourceMethod) {
    this.sourceMethod = sourceMethod;
    return this;
  }

   /**
   * Get sourceMethod
   * @return sourceMethod
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSourceMethod() {
    return sourceMethod;
  }

  public void setSourceMethod(String sourceMethod) {
    this.sourceMethod = sourceMethod;
  }

  public InlineResponse2002ItemLocationVirtual sourceWarehouse(Long sourceWarehouse) {
    this.sourceWarehouse = sourceWarehouse;
    return this;
  }

   /**
   * Get sourceWarehouse
   * @return sourceWarehouse
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSourceWarehouse() {
    return sourceWarehouse;
  }

  public void setSourceWarehouse(Long sourceWarehouse) {
    this.sourceWarehouse = sourceWarehouse;
  }

  public InlineResponse2002ItemLocationVirtual unitRetail(Double unitRetail) {
    this.unitRetail = unitRetail;
    return this;
  }

   /**
   * Get unitRetail
   * @return unitRetail
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getUnitRetail() {
    return unitRetail;
  }

  public void setUnitRetail(Double unitRetail) {
    this.unitRetail = unitRetail;
  }

  public InlineResponse2002ItemLocationVirtual sellingUnitRetail(Double sellingUnitRetail) {
    this.sellingUnitRetail = sellingUnitRetail;
    return this;
  }

   /**
   * Get sellingUnitRetail
   * @return sellingUnitRetail
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getSellingUnitRetail() {
    return sellingUnitRetail;
  }

  public void setSellingUnitRetail(Double sellingUnitRetail) {
    this.sellingUnitRetail = sellingUnitRetail;
  }

  public InlineResponse2002ItemLocationVirtual sellingUom(String sellingUom) {
    this.sellingUom = sellingUom;
    return this;
  }

   /**
   * Get sellingUom
   * @return sellingUom
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSellingUom() {
    return sellingUom;
  }

  public void setSellingUom(String sellingUom) {
    this.sellingUom = sellingUom;
  }

  public InlineResponse2002ItemLocationVirtual rangedIndicator(String rangedIndicator) {
    this.rangedIndicator = rangedIndicator;
    return this;
  }

   /**
   * Get rangedIndicator
   * @return rangedIndicator
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getRangedIndicator() {
    return rangedIndicator;
  }

  public void setRangedIndicator(String rangedIndicator) {
    this.rangedIndicator = rangedIndicator;
  }

  public InlineResponse2002ItemLocationVirtual created(DateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getCreated() {
    return created;
  }

  public void setCreated(DateTime created) {
    this.created = created;
  }

  public InlineResponse2002ItemLocationVirtual modified(DateTime modified) {
    this.modified = modified;
    return this;
  }

   /**
   * Get modified
   * @return modified
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getModified() {
    return modified;
  }

  public void setModified(DateTime modified) {
    this.modified = modified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002ItemLocationVirtual inlineResponse2002ItemLocationVirtual = (InlineResponse2002ItemLocationVirtual) o;
    return Objects.equals(this.itemId, inlineResponse2002ItemLocationVirtual.itemId) &&
        Objects.equals(this.locationId, inlineResponse2002ItemLocationVirtual.locationId) &&
        Objects.equals(this.locationType, inlineResponse2002ItemLocationVirtual.locationType) &&
        Objects.equals(this.localItemDesc, inlineResponse2002ItemLocationVirtual.localItemDesc) &&
        Objects.equals(this.localShortDesc, inlineResponse2002ItemLocationVirtual.localShortDesc) &&
        Objects.equals(this.status, inlineResponse2002ItemLocationVirtual.status) &&
        Objects.equals(this.primarySupplierId, inlineResponse2002ItemLocationVirtual.primarySupplierId) &&
        Objects.equals(this.primaryCountryId, inlineResponse2002ItemLocationVirtual.primaryCountryId) &&
        Objects.equals(this.receiveAsType, inlineResponse2002ItemLocationVirtual.receiveAsType) &&
        Objects.equals(this.isItemTaxable, inlineResponse2002ItemLocationVirtual.isItemTaxable) &&
        Objects.equals(this.sourceMethod, inlineResponse2002ItemLocationVirtual.sourceMethod) &&
        Objects.equals(this.sourceWarehouse, inlineResponse2002ItemLocationVirtual.sourceWarehouse) &&
        Objects.equals(this.unitRetail, inlineResponse2002ItemLocationVirtual.unitRetail) &&
        Objects.equals(this.sellingUnitRetail, inlineResponse2002ItemLocationVirtual.sellingUnitRetail) &&
        Objects.equals(this.sellingUom, inlineResponse2002ItemLocationVirtual.sellingUom) &&
        Objects.equals(this.rangedIndicator, inlineResponse2002ItemLocationVirtual.rangedIndicator) &&
        Objects.equals(this.created, inlineResponse2002ItemLocationVirtual.created) &&
        Objects.equals(this.modified, inlineResponse2002ItemLocationVirtual.modified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemId, locationId, locationType, localItemDesc, localShortDesc, status, primarySupplierId, primaryCountryId, receiveAsType, isItemTaxable, sourceMethod, sourceWarehouse, unitRetail, sellingUnitRetail, sellingUom, rangedIndicator, created, modified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002ItemLocationVirtual {\n");
    
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    locationType: ").append(toIndentedString(locationType)).append("\n");
    sb.append("    localItemDesc: ").append(toIndentedString(localItemDesc)).append("\n");
    sb.append("    localShortDesc: ").append(toIndentedString(localShortDesc)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    primarySupplierId: ").append(toIndentedString(primarySupplierId)).append("\n");
    sb.append("    primaryCountryId: ").append(toIndentedString(primaryCountryId)).append("\n");
    sb.append("    receiveAsType: ").append(toIndentedString(receiveAsType)).append("\n");
    sb.append("    isItemTaxable: ").append(toIndentedString(isItemTaxable)).append("\n");
    sb.append("    sourceMethod: ").append(toIndentedString(sourceMethod)).append("\n");
    sb.append("    sourceWarehouse: ").append(toIndentedString(sourceWarehouse)).append("\n");
    sb.append("    unitRetail: ").append(toIndentedString(unitRetail)).append("\n");
    sb.append("    sellingUnitRetail: ").append(toIndentedString(sellingUnitRetail)).append("\n");
    sb.append("    sellingUom: ").append(toIndentedString(sellingUom)).append("\n");
    sb.append("    rangedIndicator: ").append(toIndentedString(rangedIndicator)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

