/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * InlineResponse2002ItemSupplier
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
public class InlineResponse2002ItemSupplier {
  @SerializedName("ItemId")
  private String itemId = null;

  @SerializedName("SupplierId")
  private String supplierId = null;

  @SerializedName("IsPrimarySupplier")
  private String isPrimarySupplier = null;

  @SerializedName("SupplierProductNumber")
  private String supplierProductNumber = null;

  @SerializedName("ConsignmentRate")
  private Double consignmentRate = null;

  @SerializedName("SuppDiff1")
  private String suppDiff1 = null;

  @SerializedName("SuppDiff2")
  private String suppDiff2 = null;

  @SerializedName("SuppDiff3")
  private String suppDiff3 = null;

  @SerializedName("SuppDiff4")
  private String suppDiff4 = null;

  @SerializedName("Created")
  private DateTime created = null;

  @SerializedName("Modified")
  private DateTime modified = null;

  public InlineResponse2002ItemSupplier itemId(String itemId) {
    this.itemId = itemId;
    return this;
  }

   /**
   * Get itemId
   * @return itemId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getItemId() {
    return itemId;
  }

  public void setItemId(String itemId) {
    this.itemId = itemId;
  }

  public InlineResponse2002ItemSupplier supplierId(String supplierId) {
    this.supplierId = supplierId;
    return this;
  }

   /**
   * Get supplierId
   * @return supplierId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getSupplierId() {
    return supplierId;
  }

  public void setSupplierId(String supplierId) {
    this.supplierId = supplierId;
  }

  public InlineResponse2002ItemSupplier isPrimarySupplier(String isPrimarySupplier) {
    this.isPrimarySupplier = isPrimarySupplier;
    return this;
  }

   /**
   * Get isPrimarySupplier
   * @return isPrimarySupplier
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getIsPrimarySupplier() {
    return isPrimarySupplier;
  }

  public void setIsPrimarySupplier(String isPrimarySupplier) {
    this.isPrimarySupplier = isPrimarySupplier;
  }

  public InlineResponse2002ItemSupplier supplierProductNumber(String supplierProductNumber) {
    this.supplierProductNumber = supplierProductNumber;
    return this;
  }

   /**
   * Get supplierProductNumber
   * @return supplierProductNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSupplierProductNumber() {
    return supplierProductNumber;
  }

  public void setSupplierProductNumber(String supplierProductNumber) {
    this.supplierProductNumber = supplierProductNumber;
  }

  public InlineResponse2002ItemSupplier consignmentRate(Double consignmentRate) {
    this.consignmentRate = consignmentRate;
    return this;
  }

   /**
   * Get consignmentRate
   * @return consignmentRate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getConsignmentRate() {
    return consignmentRate;
  }

  public void setConsignmentRate(Double consignmentRate) {
    this.consignmentRate = consignmentRate;
  }

  public InlineResponse2002ItemSupplier suppDiff1(String suppDiff1) {
    this.suppDiff1 = suppDiff1;
    return this;
  }

   /**
   * Get suppDiff1
   * @return suppDiff1
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSuppDiff1() {
    return suppDiff1;
  }

  public void setSuppDiff1(String suppDiff1) {
    this.suppDiff1 = suppDiff1;
  }

  public InlineResponse2002ItemSupplier suppDiff2(String suppDiff2) {
    this.suppDiff2 = suppDiff2;
    return this;
  }

   /**
   * Get suppDiff2
   * @return suppDiff2
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSuppDiff2() {
    return suppDiff2;
  }

  public void setSuppDiff2(String suppDiff2) {
    this.suppDiff2 = suppDiff2;
  }

  public InlineResponse2002ItemSupplier suppDiff3(String suppDiff3) {
    this.suppDiff3 = suppDiff3;
    return this;
  }

   /**
   * Get suppDiff3
   * @return suppDiff3
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSuppDiff3() {
    return suppDiff3;
  }

  public void setSuppDiff3(String suppDiff3) {
    this.suppDiff3 = suppDiff3;
  }

  public InlineResponse2002ItemSupplier suppDiff4(String suppDiff4) {
    this.suppDiff4 = suppDiff4;
    return this;
  }

   /**
   * Get suppDiff4
   * @return suppDiff4
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSuppDiff4() {
    return suppDiff4;
  }

  public void setSuppDiff4(String suppDiff4) {
    this.suppDiff4 = suppDiff4;
  }

  public InlineResponse2002ItemSupplier created(DateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getCreated() {
    return created;
  }

  public void setCreated(DateTime created) {
    this.created = created;
  }

  public InlineResponse2002ItemSupplier modified(DateTime modified) {
    this.modified = modified;
    return this;
  }

   /**
   * Get modified
   * @return modified
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getModified() {
    return modified;
  }

  public void setModified(DateTime modified) {
    this.modified = modified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002ItemSupplier inlineResponse2002ItemSupplier = (InlineResponse2002ItemSupplier) o;
    return Objects.equals(this.itemId, inlineResponse2002ItemSupplier.itemId) &&
        Objects.equals(this.supplierId, inlineResponse2002ItemSupplier.supplierId) &&
        Objects.equals(this.isPrimarySupplier, inlineResponse2002ItemSupplier.isPrimarySupplier) &&
        Objects.equals(this.supplierProductNumber, inlineResponse2002ItemSupplier.supplierProductNumber) &&
        Objects.equals(this.consignmentRate, inlineResponse2002ItemSupplier.consignmentRate) &&
        Objects.equals(this.suppDiff1, inlineResponse2002ItemSupplier.suppDiff1) &&
        Objects.equals(this.suppDiff2, inlineResponse2002ItemSupplier.suppDiff2) &&
        Objects.equals(this.suppDiff3, inlineResponse2002ItemSupplier.suppDiff3) &&
        Objects.equals(this.suppDiff4, inlineResponse2002ItemSupplier.suppDiff4) &&
        Objects.equals(this.created, inlineResponse2002ItemSupplier.created) &&
        Objects.equals(this.modified, inlineResponse2002ItemSupplier.modified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemId, supplierId, isPrimarySupplier, supplierProductNumber, consignmentRate, suppDiff1, suppDiff2, suppDiff3, suppDiff4, created, modified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002ItemSupplier {\n");
    
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    supplierId: ").append(toIndentedString(supplierId)).append("\n");
    sb.append("    isPrimarySupplier: ").append(toIndentedString(isPrimarySupplier)).append("\n");
    sb.append("    supplierProductNumber: ").append(toIndentedString(supplierProductNumber)).append("\n");
    sb.append("    consignmentRate: ").append(toIndentedString(consignmentRate)).append("\n");
    sb.append("    suppDiff1: ").append(toIndentedString(suppDiff1)).append("\n");
    sb.append("    suppDiff2: ").append(toIndentedString(suppDiff2)).append("\n");
    sb.append("    suppDiff3: ").append(toIndentedString(suppDiff3)).append("\n");
    sb.append("    suppDiff4: ").append(toIndentedString(suppDiff4)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

