/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * InlineResponse2002ItemBarcode
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
public class InlineResponse2002ItemBarcode {
  @SerializedName("ItemId")
  private String itemId = null;

  @SerializedName("ItemParentId")
  private String itemParentId = null;

  @SerializedName("IsSKUPrimaryBarcode")
  private String isSKUPrimaryBarcode = null;

  @SerializedName("VariableUPCFormatId")
  private String variableUPCFormatId = null;

  @SerializedName("VariableWeightUPCPrefix")
  private String variableWeightUPCPrefix = null;

  @SerializedName("ItemNumberType")
  private String itemNumberType = null;

  @SerializedName("Created")
  private DateTime created = null;

  @SerializedName("Modified")
  private DateTime modified = null;

  public InlineResponse2002ItemBarcode itemId(String itemId) {
    this.itemId = itemId;
    return this;
  }

   /**
   * Get itemId
   * @return itemId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getItemId() {
    return itemId;
  }

  public void setItemId(String itemId) {
    this.itemId = itemId;
  }

  public InlineResponse2002ItemBarcode itemParentId(String itemParentId) {
    this.itemParentId = itemParentId;
    return this;
  }

   /**
   * Get itemParentId
   * @return itemParentId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getItemParentId() {
    return itemParentId;
  }

  public void setItemParentId(String itemParentId) {
    this.itemParentId = itemParentId;
  }

  public InlineResponse2002ItemBarcode isSKUPrimaryBarcode(String isSKUPrimaryBarcode) {
    this.isSKUPrimaryBarcode = isSKUPrimaryBarcode;
    return this;
  }

   /**
   * Get isSKUPrimaryBarcode
   * @return isSKUPrimaryBarcode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIsSKUPrimaryBarcode() {
    return isSKUPrimaryBarcode;
  }

  public void setIsSKUPrimaryBarcode(String isSKUPrimaryBarcode) {
    this.isSKUPrimaryBarcode = isSKUPrimaryBarcode;
  }

  public InlineResponse2002ItemBarcode variableUPCFormatId(String variableUPCFormatId) {
    this.variableUPCFormatId = variableUPCFormatId;
    return this;
  }

   /**
   * Get variableUPCFormatId
   * @return variableUPCFormatId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVariableUPCFormatId() {
    return variableUPCFormatId;
  }

  public void setVariableUPCFormatId(String variableUPCFormatId) {
    this.variableUPCFormatId = variableUPCFormatId;
  }

  public InlineResponse2002ItemBarcode variableWeightUPCPrefix(String variableWeightUPCPrefix) {
    this.variableWeightUPCPrefix = variableWeightUPCPrefix;
    return this;
  }

   /**
   * Get variableWeightUPCPrefix
   * @return variableWeightUPCPrefix
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVariableWeightUPCPrefix() {
    return variableWeightUPCPrefix;
  }

  public void setVariableWeightUPCPrefix(String variableWeightUPCPrefix) {
    this.variableWeightUPCPrefix = variableWeightUPCPrefix;
  }

  public InlineResponse2002ItemBarcode itemNumberType(String itemNumberType) {
    this.itemNumberType = itemNumberType;
    return this;
  }

   /**
   * Get itemNumberType
   * @return itemNumberType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getItemNumberType() {
    return itemNumberType;
  }

  public void setItemNumberType(String itemNumberType) {
    this.itemNumberType = itemNumberType;
  }

  public InlineResponse2002ItemBarcode created(DateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getCreated() {
    return created;
  }

  public void setCreated(DateTime created) {
    this.created = created;
  }

  public InlineResponse2002ItemBarcode modified(DateTime modified) {
    this.modified = modified;
    return this;
  }

   /**
   * Get modified
   * @return modified
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getModified() {
    return modified;
  }

  public void setModified(DateTime modified) {
    this.modified = modified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002ItemBarcode inlineResponse2002ItemBarcode = (InlineResponse2002ItemBarcode) o;
    return Objects.equals(this.itemId, inlineResponse2002ItemBarcode.itemId) &&
        Objects.equals(this.itemParentId, inlineResponse2002ItemBarcode.itemParentId) &&
        Objects.equals(this.isSKUPrimaryBarcode, inlineResponse2002ItemBarcode.isSKUPrimaryBarcode) &&
        Objects.equals(this.variableUPCFormatId, inlineResponse2002ItemBarcode.variableUPCFormatId) &&
        Objects.equals(this.variableWeightUPCPrefix, inlineResponse2002ItemBarcode.variableWeightUPCPrefix) &&
        Objects.equals(this.itemNumberType, inlineResponse2002ItemBarcode.itemNumberType) &&
        Objects.equals(this.created, inlineResponse2002ItemBarcode.created) &&
        Objects.equals(this.modified, inlineResponse2002ItemBarcode.modified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemId, itemParentId, isSKUPrimaryBarcode, variableUPCFormatId, variableWeightUPCPrefix, itemNumberType, created, modified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002ItemBarcode {\n");
    
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    itemParentId: ").append(toIndentedString(itemParentId)).append("\n");
    sb.append("    isSKUPrimaryBarcode: ").append(toIndentedString(isSKUPrimaryBarcode)).append("\n");
    sb.append("    variableUPCFormatId: ").append(toIndentedString(variableUPCFormatId)).append("\n");
    sb.append("    variableWeightUPCPrefix: ").append(toIndentedString(variableWeightUPCPrefix)).append("\n");
    sb.append("    itemNumberType: ").append(toIndentedString(itemNumberType)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

