/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * InlineResponse200
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
@Document(collection = "Availability")
public class InlineResponse200 {
  @SerializedName("SequenceId")
  private Long sequenceId = null;

  @SerializedName("TimeStamp")
  private Long timeStamp = null;

  @SerializedName("GroupStockId")
  @Id
  private String groupStockId = null;

  @SerializedName("StockLevel")
  private Integer stockLevel = null;

  @SerializedName("StockThreshold")
  private Integer stockThreshold = null;

  @SerializedName("PreOrderLevel")
  private Integer preOrderLevel = null;

  @SerializedName("PreOrderThreshold")
  private Integer preOrderThreshold = null;

  @SerializedName("BackOrderLevel")
  private Integer backOrderLevel = null;

  @SerializedName("BackOrderThreshold")
  private Integer backOrderThreshold = null;

  public InlineResponse200 sequenceId(Long sequenceId) {
    this.sequenceId = sequenceId;
    return this;
  }

   /**
   * Get sequenceId
   * @return sequenceId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSequenceId() {
    return sequenceId;
  }

  public void setSequenceId(Long sequenceId) {
    this.sequenceId = sequenceId;
  }

  public InlineResponse200 timeStamp(Long timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * Get timeStamp
   * @return timeStamp
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTimeStamp() {
    return timeStamp;
  }

  public void setTimeStamp(Long timeStamp) {
    this.timeStamp = timeStamp;
  }

  public InlineResponse200 groupStockId(String groupStockId) {
    this.groupStockId = groupStockId;
    return this;
  }

   /**
   * Get groupStockId
   * @return groupStockId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGroupStockId() {
    return groupStockId;
  }

  public void setGroupStockId(String groupStockId) {
    this.groupStockId = groupStockId;
  }

  public InlineResponse200 stockLevel(Integer stockLevel) {
    this.stockLevel = stockLevel;
    return this;
  }

   /**
   * Get stockLevel
   * @return stockLevel
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStockLevel() {
    return stockLevel;
  }

  public void setStockLevel(Integer stockLevel) {
    this.stockLevel = stockLevel;
  }

  public InlineResponse200 stockThreshold(Integer stockThreshold) {
    this.stockThreshold = stockThreshold;
    return this;
  }

   /**
   * Get stockThreshold
   * @return stockThreshold
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStockThreshold() {
    return stockThreshold;
  }

  public void setStockThreshold(Integer stockThreshold) {
    this.stockThreshold = stockThreshold;
  }

  public InlineResponse200 preOrderLevel(Integer preOrderLevel) {
    this.preOrderLevel = preOrderLevel;
    return this;
  }

   /**
   * Get preOrderLevel
   * @return preOrderLevel
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPreOrderLevel() {
    return preOrderLevel;
  }

  public void setPreOrderLevel(Integer preOrderLevel) {
    this.preOrderLevel = preOrderLevel;
  }

  public InlineResponse200 preOrderThreshold(Integer preOrderThreshold) {
    this.preOrderThreshold = preOrderThreshold;
    return this;
  }

   /**
   * Get preOrderThreshold
   * @return preOrderThreshold
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPreOrderThreshold() {
    return preOrderThreshold;
  }

  public void setPreOrderThreshold(Integer preOrderThreshold) {
    this.preOrderThreshold = preOrderThreshold;
  }

  public InlineResponse200 backOrderLevel(Integer backOrderLevel) {
    this.backOrderLevel = backOrderLevel;
    return this;
  }

   /**
   * Get backOrderLevel
   * @return backOrderLevel
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBackOrderLevel() {
    return backOrderLevel;
  }

  public void setBackOrderLevel(Integer backOrderLevel) {
    this.backOrderLevel = backOrderLevel;
  }

  public InlineResponse200 backOrderThreshold(Integer backOrderThreshold) {
    this.backOrderThreshold = backOrderThreshold;
    return this;
  }

   /**
   * Get backOrderThreshold
   * @return backOrderThreshold
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBackOrderThreshold() {
    return backOrderThreshold;
  }

  public void setBackOrderThreshold(Integer backOrderThreshold) {
    this.backOrderThreshold = backOrderThreshold;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.sequenceId, inlineResponse200.sequenceId) &&
        Objects.equals(this.timeStamp, inlineResponse200.timeStamp) &&
        Objects.equals(this.groupStockId, inlineResponse200.groupStockId) &&
        Objects.equals(this.stockLevel, inlineResponse200.stockLevel) &&
        Objects.equals(this.stockThreshold, inlineResponse200.stockThreshold) &&
        Objects.equals(this.preOrderLevel, inlineResponse200.preOrderLevel) &&
        Objects.equals(this.preOrderThreshold, inlineResponse200.preOrderThreshold) &&
        Objects.equals(this.backOrderLevel, inlineResponse200.backOrderLevel) &&
        Objects.equals(this.backOrderThreshold, inlineResponse200.backOrderThreshold);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sequenceId, timeStamp, groupStockId, stockLevel, stockThreshold, preOrderLevel, preOrderThreshold, backOrderLevel, backOrderThreshold);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    sequenceId: ").append(toIndentedString(sequenceId)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("    groupStockId: ").append(toIndentedString(groupStockId)).append("\n");
    sb.append("    stockLevel: ").append(toIndentedString(stockLevel)).append("\n");
    sb.append("    stockThreshold: ").append(toIndentedString(stockThreshold)).append("\n");
    sb.append("    preOrderLevel: ").append(toIndentedString(preOrderLevel)).append("\n");
    sb.append("    preOrderThreshold: ").append(toIndentedString(preOrderThreshold)).append("\n");
    sb.append("    backOrderLevel: ").append(toIndentedString(backOrderLevel)).append("\n");
    sb.append("    backOrderThreshold: ").append(toIndentedString(backOrderThreshold)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

