/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Apiv1crcordersBillingAddress;
import io.swagger.client.model.Apiv1crcordersCustomer;
import io.swagger.client.model.Apiv1crcordersItems;
import io.swagger.client.model.Apiv1crcordersPaymentDetails;
import io.swagger.client.model.Apiv1crcordersPromotionList;
import io.swagger.client.model.Apiv1crcordersShipping;
import io.swagger.client.model.Apiv1crcordersShippingAddress;
import org.springframework.data.annotation.Id;
import org.springframework.hateoas.ResourceSupport;

import java.util.ArrayList;
import java.util.List;

/**
 * Order
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
public class Order extends ResourceSupport {
  @SerializedName("OrderId")
  private String id = null;

  @SerializedName("OriginalOrderId")
  @Id
  private String originalOrderId = null;

  @SerializedName("Source")
  private String source = null;

  @SerializedName("TimeStamp")
  private String timeStamp = null;

  @SerializedName("CustomerViewingCurrency")
  private String customerViewingCurrency = null;

  @SerializedName("OrderCurrency")
  private String orderCurrency = null;

  @SerializedName("ExchangeRate")
  private Double exchangeRate = null;

  @SerializedName("OrderAmount")
  private Double orderAmount = null;

  @SerializedName("OrderDiscount")
  private Double orderDiscount = null;

  @SerializedName("PromotionList")
  private List<Apiv1crcordersPromotionList> promotionList = new ArrayList<Apiv1crcordersPromotionList>();

  @SerializedName("Customer")
  private Apiv1crcordersCustomer customer = null;

  @SerializedName("BillingAddress")
  private Apiv1crcordersBillingAddress billingAddress = null;

  @SerializedName("ShippingAddress")
  private Apiv1crcordersShippingAddress shippingAddress = null;

  @SerializedName("Shipping")
  private Apiv1crcordersShipping shipping = null;

  @SerializedName("PaymentDetails")
  private List<Apiv1crcordersPaymentDetails> paymentDetails = new ArrayList<Apiv1crcordersPaymentDetails>();

  @SerializedName("Items")
  private List<Apiv1crcordersItems> items = new ArrayList<Apiv1crcordersItems>();

  public Order id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOrderId() {
    return id;
  }

  public void getOrderId(String id) {
    this.id = id;
  }

  public Order originalOrderId(String originalOrderId) {
    this.originalOrderId = originalOrderId;
    return this;
  }

   /**
   * Get originalOrderId
   * @return originalOrderId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOriginalOrderId() {
    return originalOrderId;
  }

  public void setOriginalOrderId(String originalOrderId) {
    this.originalOrderId = originalOrderId;
  }

  public Order source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public Order timeStamp(String timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * Get timeStamp
   * @return timeStamp
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTimeStamp() {
    return timeStamp;
  }

  public void setTimeStamp(String timeStamp) {
    this.timeStamp = timeStamp;
  }

  public Order customerViewingCurrency(String customerViewingCurrency) {
    this.customerViewingCurrency = customerViewingCurrency;
    return this;
  }

   /**
   * Get customerViewingCurrency
   * @return customerViewingCurrency
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCustomerViewingCurrency() {
    return customerViewingCurrency;
  }

  public void setCustomerViewingCurrency(String customerViewingCurrency) {
    this.customerViewingCurrency = customerViewingCurrency;
  }

  public Order orderCurrency(String orderCurrency) {
    this.orderCurrency = orderCurrency;
    return this;
  }

   /**
   * Get orderCurrency
   * @return orderCurrency
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOrderCurrency() {
    return orderCurrency;
  }

  public void setOrderCurrency(String orderCurrency) {
    this.orderCurrency = orderCurrency;
  }

  public Order exchangeRate(Double exchangeRate) {
    this.exchangeRate = exchangeRate;
    return this;
  }

   /**
   * Get exchangeRate
   * @return exchangeRate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getExchangeRate() {
    return exchangeRate;
  }

  public void setExchangeRate(Double exchangeRate) {
    this.exchangeRate = exchangeRate;
  }

  public Order orderAmount(Double orderAmount) {
    this.orderAmount = orderAmount;
    return this;
  }

   /**
   * Get orderAmount
   * @return orderAmount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getOrderAmount() {
    return orderAmount;
  }

  public void setOrderAmount(Double orderAmount) {
    this.orderAmount = orderAmount;
  }

  public Order orderDiscount(Double orderDiscount) {
    this.orderDiscount = orderDiscount;
    return this;
  }

   /**
   * Get orderDiscount
   * @return orderDiscount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getOrderDiscount() {
    return orderDiscount;
  }

  public void setOrderDiscount(Double orderDiscount) {
    this.orderDiscount = orderDiscount;
  }

  public Order promotionList(List<Apiv1crcordersPromotionList> promotionList) {
    this.promotionList = promotionList;
    return this;
  }

  public Order addPromotionListItem(Apiv1crcordersPromotionList promotionListItem) {
    this.promotionList.add(promotionListItem);
    return this;
  }

   /**
   * Get promotionList
   * @return promotionList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Apiv1crcordersPromotionList> getPromotionList() {
    return promotionList;
  }

  public void setPromotionList(List<Apiv1crcordersPromotionList> promotionList) {
    this.promotionList = promotionList;
  }

  public Order customer(Apiv1crcordersCustomer customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  @ApiModelProperty(example = "null", value = "")
  public Apiv1crcordersCustomer getCustomer() {
    return customer;
  }

  public void setCustomer(Apiv1crcordersCustomer customer) {
    this.customer = customer;
  }

  public Order billingAddress(Apiv1crcordersBillingAddress billingAddress) {
    this.billingAddress = billingAddress;
    return this;
  }

   /**
   * Get billingAddress
   * @return billingAddress
  **/
  @ApiModelProperty(example = "null", value = "")
  public Apiv1crcordersBillingAddress getBillingAddress() {
    return billingAddress;
  }

  public void setBillingAddress(Apiv1crcordersBillingAddress billingAddress) {
    this.billingAddress = billingAddress;
  }

  public Order shippingAddress(Apiv1crcordersShippingAddress shippingAddress) {
    this.shippingAddress = shippingAddress;
    return this;
  }

   /**
   * Get shippingAddress
   * @return shippingAddress
  **/
  @ApiModelProperty(example = "null", value = "")
  public Apiv1crcordersShippingAddress getShippingAddress() {
    return shippingAddress;
  }

  public void setShippingAddress(Apiv1crcordersShippingAddress shippingAddress) {
    this.shippingAddress = shippingAddress;
  }

  public Order shipping(Apiv1crcordersShipping shipping) {
    this.shipping = shipping;
    return this;
  }

   /**
   * Get shipping
   * @return shipping
  **/
  @ApiModelProperty(example = "null", value = "")
  public Apiv1crcordersShipping getShipping() {
    return shipping;
  }

  public void setShipping(Apiv1crcordersShipping shipping) {
    this.shipping = shipping;
  }

  public Order paymentDetails(List<Apiv1crcordersPaymentDetails> paymentDetails) {
    this.paymentDetails = paymentDetails;
    return this;
  }

  public Order addPaymentDetailsItem(Apiv1crcordersPaymentDetails paymentDetailsItem) {
    this.paymentDetails.add(paymentDetailsItem);
    return this;
  }

   /**
   * Get paymentDetails
   * @return paymentDetails
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Apiv1crcordersPaymentDetails> getPaymentDetails() {
    return paymentDetails;
  }

  public void setPaymentDetails(List<Apiv1crcordersPaymentDetails> paymentDetails) {
    this.paymentDetails = paymentDetails;
  }

  public Order items(List<Apiv1crcordersItems> items) {
    this.items = items;
    return this;
  }

  public Order addItemsItem(Apiv1crcordersItems itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Apiv1crcordersItems> getItems() {
    return items;
  }

  public void setItems(List<Apiv1crcordersItems> items) {
    this.items = items;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Order order = (Order) o;
    return Objects.equals(this.id, order.id) &&
        Objects.equals(this.originalOrderId, order.originalOrderId) &&
        Objects.equals(this.source, order.source) &&
        Objects.equals(this.timeStamp, order.timeStamp) &&
        Objects.equals(this.customerViewingCurrency, order.customerViewingCurrency) &&
        Objects.equals(this.orderCurrency, order.orderCurrency) &&
        Objects.equals(this.exchangeRate, order.exchangeRate) &&
        Objects.equals(this.orderAmount, order.orderAmount) &&
        Objects.equals(this.orderDiscount, order.orderDiscount) &&
        Objects.equals(this.promotionList, order.promotionList) &&
        Objects.equals(this.customer, order.customer) &&
        Objects.equals(this.billingAddress, order.billingAddress) &&
        Objects.equals(this.shippingAddress, order.shippingAddress) &&
        Objects.equals(this.shipping, order.shipping) &&
        Objects.equals(this.paymentDetails, order.paymentDetails) &&
        Objects.equals(this.items, order.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, originalOrderId, source, timeStamp, customerViewingCurrency, orderCurrency, exchangeRate, orderAmount, orderDiscount, promotionList, customer, billingAddress, shippingAddress, shipping, paymentDetails, items);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Order {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    originalOrderId: ").append(toIndentedString(originalOrderId)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("    customerViewingCurrency: ").append(toIndentedString(customerViewingCurrency)).append("\n");
    sb.append("    orderCurrency: ").append(toIndentedString(orderCurrency)).append("\n");
    sb.append("    exchangeRate: ").append(toIndentedString(exchangeRate)).append("\n");
    sb.append("    orderAmount: ").append(toIndentedString(orderAmount)).append("\n");
    sb.append("    orderDiscount: ").append(toIndentedString(orderDiscount)).append("\n");
    sb.append("    promotionList: ").append(toIndentedString(promotionList)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    billingAddress: ").append(toIndentedString(billingAddress)).append("\n");
    sb.append("    shippingAddress: ").append(toIndentedString(shippingAddress)).append("\n");
    sb.append("    shipping: ").append(toIndentedString(shipping)).append("\n");
    sb.append("    paymentDetails: ").append(toIndentedString(paymentDetails)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

