/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * WiggleCRCModelsATGOrderCreationPaymentTypesCreditCard
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
public class WiggleCRCModelsATGOrderCreationPaymentTypesCreditCard {
  @SerializedName("RealVaultPayerRef")
  private String realVaultPayerRef = null;

  @SerializedName("RealVaultCardRef")
  private String realVaultCardRef = null;

  @SerializedName("PaymentAmount")
  private Double paymentAmount = null;

  @SerializedName("Reference")
  private String reference = null;

  public WiggleCRCModelsATGOrderCreationPaymentTypesCreditCard realVaultPayerRef(String realVaultPayerRef) {
    this.realVaultPayerRef = realVaultPayerRef;
    return this;
  }

   /**
   * Get realVaultPayerRef
   * @return realVaultPayerRef
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRealVaultPayerRef() {
    return realVaultPayerRef;
  }

  public void setRealVaultPayerRef(String realVaultPayerRef) {
    this.realVaultPayerRef = realVaultPayerRef;
  }

  public WiggleCRCModelsATGOrderCreationPaymentTypesCreditCard realVaultCardRef(String realVaultCardRef) {
    this.realVaultCardRef = realVaultCardRef;
    return this;
  }

   /**
   * Get realVaultCardRef
   * @return realVaultCardRef
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRealVaultCardRef() {
    return realVaultCardRef;
  }

  public void setRealVaultCardRef(String realVaultCardRef) {
    this.realVaultCardRef = realVaultCardRef;
  }

  public WiggleCRCModelsATGOrderCreationPaymentTypesCreditCard paymentAmount(Double paymentAmount) {
    this.paymentAmount = paymentAmount;
    return this;
  }

   /**
   * Get paymentAmount
   * @return paymentAmount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getPaymentAmount() {
    return paymentAmount;
  }

  public void setPaymentAmount(Double paymentAmount) {
    this.paymentAmount = paymentAmount;
  }

  public WiggleCRCModelsATGOrderCreationPaymentTypesCreditCard reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WiggleCRCModelsATGOrderCreationPaymentTypesCreditCard wiggleCRCModelsATGOrderCreationPaymentTypesCreditCard = (WiggleCRCModelsATGOrderCreationPaymentTypesCreditCard) o;
    return Objects.equals(this.realVaultPayerRef, wiggleCRCModelsATGOrderCreationPaymentTypesCreditCard.realVaultPayerRef) &&
        Objects.equals(this.realVaultCardRef, wiggleCRCModelsATGOrderCreationPaymentTypesCreditCard.realVaultCardRef) &&
        Objects.equals(this.paymentAmount, wiggleCRCModelsATGOrderCreationPaymentTypesCreditCard.paymentAmount) &&
        Objects.equals(this.reference, wiggleCRCModelsATGOrderCreationPaymentTypesCreditCard.reference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(realVaultPayerRef, realVaultCardRef, paymentAmount, reference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WiggleCRCModelsATGOrderCreationPaymentTypesCreditCard {\n");
    
    sb.append("    realVaultPayerRef: ").append(toIndentedString(realVaultPayerRef)).append("\n");
    sb.append("    realVaultCardRef: ").append(toIndentedString(realVaultCardRef)).append("\n");
    sb.append("    paymentAmount: ").append(toIndentedString(paymentAmount)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

