/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * WiggleCRCModelsATGOrderCreationPaymentTypesFinance
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
public class WiggleCRCModelsATGOrderCreationPaymentTypesFinance {
  @SerializedName("VoucherReference")
  private String voucherReference = null;

  @SerializedName("Amount")
  private Double amount = null;

  public WiggleCRCModelsATGOrderCreationPaymentTypesFinance voucherReference(String voucherReference) {
    this.voucherReference = voucherReference;
    return this;
  }

   /**
   * Get voucherReference
   * @return voucherReference
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVoucherReference() {
    return voucherReference;
  }

  public void setVoucherReference(String voucherReference) {
    this.voucherReference = voucherReference;
  }

  public WiggleCRCModelsATGOrderCreationPaymentTypesFinance amount(Double amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getAmount() {
    return amount;
  }

  public void setAmount(Double amount) {
    this.amount = amount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WiggleCRCModelsATGOrderCreationPaymentTypesFinance wiggleCRCModelsATGOrderCreationPaymentTypesFinance = (WiggleCRCModelsATGOrderCreationPaymentTypesFinance) o;
    return Objects.equals(this.voucherReference, wiggleCRCModelsATGOrderCreationPaymentTypesFinance.voucherReference) &&
        Objects.equals(this.amount, wiggleCRCModelsATGOrderCreationPaymentTypesFinance.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(voucherReference, amount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WiggleCRCModelsATGOrderCreationPaymentTypesFinance {\n");
    
    sb.append("    voucherReference: ").append(toIndentedString(voucherReference)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

