/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * WiggleCRCModelsATGOrderCreationPaymentTypesPayPal
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
public class WiggleCRCModelsATGOrderCreationPaymentTypesPayPal {
  @SerializedName("PayPalTransactionId")
  private String payPalTransactionId = null;

  @SerializedName("PaymentAmount")
  private Double paymentAmount = null;

  @SerializedName("MarkedAsChargedByAgent")
  private Boolean markedAsChargedByAgent = null;

  @SerializedName("Reference")
  private String reference = null;

  /**
   * Gets or Sets action
   */
  public enum ActionEnum {
    @SerializedName("0")
    NUMBER_0(0),
    
    @SerializedName("1")
    NUMBER_1(1);

    private Integer value;

    ActionEnum(Integer value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("Action")
  private ActionEnum action = null;

  public WiggleCRCModelsATGOrderCreationPaymentTypesPayPal payPalTransactionId(String payPalTransactionId) {
    this.payPalTransactionId = payPalTransactionId;
    return this;
  }

   /**
   * Get payPalTransactionId
   * @return payPalTransactionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPayPalTransactionId() {
    return payPalTransactionId;
  }

  public void setPayPalTransactionId(String payPalTransactionId) {
    this.payPalTransactionId = payPalTransactionId;
  }

  public WiggleCRCModelsATGOrderCreationPaymentTypesPayPal paymentAmount(Double paymentAmount) {
    this.paymentAmount = paymentAmount;
    return this;
  }

   /**
   * Get paymentAmount
   * @return paymentAmount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getPaymentAmount() {
    return paymentAmount;
  }

  public void setPaymentAmount(Double paymentAmount) {
    this.paymentAmount = paymentAmount;
  }

  public WiggleCRCModelsATGOrderCreationPaymentTypesPayPal markedAsChargedByAgent(Boolean markedAsChargedByAgent) {
    this.markedAsChargedByAgent = markedAsChargedByAgent;
    return this;
  }

   /**
   * Get markedAsChargedByAgent
   * @return markedAsChargedByAgent
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getMarkedAsChargedByAgent() {
    return markedAsChargedByAgent;
  }

  public void setMarkedAsChargedByAgent(Boolean markedAsChargedByAgent) {
    this.markedAsChargedByAgent = markedAsChargedByAgent;
  }

  public WiggleCRCModelsATGOrderCreationPaymentTypesPayPal reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public WiggleCRCModelsATGOrderCreationPaymentTypesPayPal action(ActionEnum action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @ApiModelProperty(example = "null", value = "")
  public ActionEnum getAction() {
    return action;
  }

  public void setAction(ActionEnum action) {
    this.action = action;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WiggleCRCModelsATGOrderCreationPaymentTypesPayPal wiggleCRCModelsATGOrderCreationPaymentTypesPayPal = (WiggleCRCModelsATGOrderCreationPaymentTypesPayPal) o;
    return Objects.equals(this.payPalTransactionId, wiggleCRCModelsATGOrderCreationPaymentTypesPayPal.payPalTransactionId) &&
        Objects.equals(this.paymentAmount, wiggleCRCModelsATGOrderCreationPaymentTypesPayPal.paymentAmount) &&
        Objects.equals(this.markedAsChargedByAgent, wiggleCRCModelsATGOrderCreationPaymentTypesPayPal.markedAsChargedByAgent) &&
        Objects.equals(this.reference, wiggleCRCModelsATGOrderCreationPaymentTypesPayPal.reference) &&
        Objects.equals(this.action, wiggleCRCModelsATGOrderCreationPaymentTypesPayPal.action);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payPalTransactionId, paymentAmount, markedAsChargedByAgent, reference, action);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WiggleCRCModelsATGOrderCreationPaymentTypesPayPal {\n");
    
    sb.append("    payPalTransactionId: ").append(toIndentedString(payPalTransactionId)).append("\n");
    sb.append("    paymentAmount: ").append(toIndentedString(paymentAmount)).append("\n");
    sb.append("    markedAsChargedByAgent: ").append(toIndentedString(markedAsChargedByAgent)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

