/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * WiggleMerchandisingItemsReaderModelsItemsItem
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
public class WiggleMerchandisingItemsReaderModelsItemsItem {
  @SerializedName("ItemId")
  private String itemId = null;

  @SerializedName("ItemNumberType")
  private String itemNumberType = null;

  @SerializedName("VariableUPCFormatId")
  private String variableUPCFormatId = null;

  @SerializedName("VariableWeightUPCPrefix")
  private Long variableWeightUPCPrefix = null;

  @SerializedName("ItemParentId")
  private String itemParentId = null;

  @SerializedName("ItemGrandparentId")
  private String itemGrandparentId = null;

  @SerializedName("IsPack")
  private String isPack = null;

  @SerializedName("ItemLevel")
  private Long itemLevel = null;

  @SerializedName("TransactionLevel")
  private Long transactionLevel = null;

  @SerializedName("Diff1")
  private String diff1 = null;

  @SerializedName("Diff1Type")
  private String diff1Type = null;

  @SerializedName("Diff2")
  private String diff2 = null;

  @SerializedName("Diff2Type")
  private String diff2Type = null;

  @SerializedName("Diff3")
  private String diff3 = null;

  @SerializedName("Diff3Type")
  private String diff3Type = null;

  @SerializedName("Diff4")
  private String diff4 = null;

  @SerializedName("Diff4Type")
  private String diff4Type = null;

  @SerializedName("DepartmentId")
  private Long departmentId = null;

  @SerializedName("DepartmentName")
  private String departmentName = null;

  @SerializedName("ClassId")
  private String classId = null;

  @SerializedName("ClassName")
  private String className = null;

  @SerializedName("SubclassId")
  private String subclassId = null;

  @SerializedName("SubclassName")
  private String subclassName = null;

  @SerializedName("Status")
  private String status = null;

  @SerializedName("LongDescription")
  private String longDescription = null;

  @SerializedName("ShortDescription")
  private String shortDescription = null;

  @SerializedName("UppercaseLongDescription")
  private String uppercaseLongDescription = null;

  @SerializedName("IsSKUPrimaryBarcode")
  private String isSKUPrimaryBarcode = null;

  @SerializedName("StandardUom")
  private String standardUom = null;

  @SerializedName("UomConvFactor")
  private Double uomConvFactor = null;

  @SerializedName("ForecastInd")
  private String forecastInd = null;

  @SerializedName("HandlingSensitivity")
  private String handlingSensitivity = null;

  @SerializedName("HandlingSensitivityDesc")
  private String handlingSensitivityDesc = null;

  @SerializedName("ConstDimenInd")
  private String constDimenInd = null;

  @SerializedName("IsSimplePack")
  private String isSimplePack = null;

  @SerializedName("PackContainsInnerPack")
  private String packContainsInnerPack = null;

  @SerializedName("PackIsSellable")
  private String packIsSellable = null;

  @SerializedName("PackIsOrderable")
  private String packIsOrderable = null;

  @SerializedName("PackType")
  private String packType = null;

  @SerializedName("OrderAsType")
  private String orderAsType = null;

  @SerializedName("Comments")
  private String comments = null;

  @SerializedName("IsPerishable")
  private String isPerishable = null;

  @SerializedName("InventoryInd")
  private String inventoryInd = null;

  @SerializedName("PurchaseType")
  private String purchaseType = null;

  @SerializedName("Created")
  private DateTime created = null;

  @SerializedName("Modified")
  private DateTime modified = null;

  public WiggleMerchandisingItemsReaderModelsItemsItem itemId(String itemId) {
    this.itemId = itemId;
    return this;
  }

   /**
   * Get itemId
   * @return itemId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getItemId() {
    return itemId;
  }

  public void setItemId(String itemId) {
    this.itemId = itemId;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem itemNumberType(String itemNumberType) {
    this.itemNumberType = itemNumberType;
    return this;
  }

   /**
   * Get itemNumberType
   * @return itemNumberType
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getItemNumberType() {
    return itemNumberType;
  }

  public void setItemNumberType(String itemNumberType) {
    this.itemNumberType = itemNumberType;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem variableUPCFormatId(String variableUPCFormatId) {
    this.variableUPCFormatId = variableUPCFormatId;
    return this;
  }

   /**
   * Get variableUPCFormatId
   * @return variableUPCFormatId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVariableUPCFormatId() {
    return variableUPCFormatId;
  }

  public void setVariableUPCFormatId(String variableUPCFormatId) {
    this.variableUPCFormatId = variableUPCFormatId;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem variableWeightUPCPrefix(Long variableWeightUPCPrefix) {
    this.variableWeightUPCPrefix = variableWeightUPCPrefix;
    return this;
  }

   /**
   * Get variableWeightUPCPrefix
   * @return variableWeightUPCPrefix
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getVariableWeightUPCPrefix() {
    return variableWeightUPCPrefix;
  }

  public void setVariableWeightUPCPrefix(Long variableWeightUPCPrefix) {
    this.variableWeightUPCPrefix = variableWeightUPCPrefix;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem itemParentId(String itemParentId) {
    this.itemParentId = itemParentId;
    return this;
  }

   /**
   * Get itemParentId
   * @return itemParentId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getItemParentId() {
    return itemParentId;
  }

  public void setItemParentId(String itemParentId) {
    this.itemParentId = itemParentId;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem itemGrandparentId(String itemGrandparentId) {
    this.itemGrandparentId = itemGrandparentId;
    return this;
  }

   /**
   * Get itemGrandparentId
   * @return itemGrandparentId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getItemGrandparentId() {
    return itemGrandparentId;
  }

  public void setItemGrandparentId(String itemGrandparentId) {
    this.itemGrandparentId = itemGrandparentId;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem isPack(String isPack) {
    this.isPack = isPack;
    return this;
  }

   /**
   * Get isPack
   * @return isPack
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getIsPack() {
    return isPack;
  }

  public void setIsPack(String isPack) {
    this.isPack = isPack;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem itemLevel(Long itemLevel) {
    this.itemLevel = itemLevel;
    return this;
  }

   /**
   * Get itemLevel
   * @return itemLevel
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Long getItemLevel() {
    return itemLevel;
  }

  public void setItemLevel(Long itemLevel) {
    this.itemLevel = itemLevel;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem transactionLevel(Long transactionLevel) {
    this.transactionLevel = transactionLevel;
    return this;
  }

   /**
   * Get transactionLevel
   * @return transactionLevel
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Long getTransactionLevel() {
    return transactionLevel;
  }

  public void setTransactionLevel(Long transactionLevel) {
    this.transactionLevel = transactionLevel;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem diff1(String diff1) {
    this.diff1 = diff1;
    return this;
  }

   /**
   * Get diff1
   * @return diff1
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDiff1() {
    return diff1;
  }

  public void setDiff1(String diff1) {
    this.diff1 = diff1;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem diff1Type(String diff1Type) {
    this.diff1Type = diff1Type;
    return this;
  }

   /**
   * Get diff1Type
   * @return diff1Type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDiff1Type() {
    return diff1Type;
  }

  public void setDiff1Type(String diff1Type) {
    this.diff1Type = diff1Type;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem diff2(String diff2) {
    this.diff2 = diff2;
    return this;
  }

   /**
   * Get diff2
   * @return diff2
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDiff2() {
    return diff2;
  }

  public void setDiff2(String diff2) {
    this.diff2 = diff2;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem diff2Type(String diff2Type) {
    this.diff2Type = diff2Type;
    return this;
  }

   /**
   * Get diff2Type
   * @return diff2Type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDiff2Type() {
    return diff2Type;
  }

  public void setDiff2Type(String diff2Type) {
    this.diff2Type = diff2Type;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem diff3(String diff3) {
    this.diff3 = diff3;
    return this;
  }

   /**
   * Get diff3
   * @return diff3
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDiff3() {
    return diff3;
  }

  public void setDiff3(String diff3) {
    this.diff3 = diff3;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem diff3Type(String diff3Type) {
    this.diff3Type = diff3Type;
    return this;
  }

   /**
   * Get diff3Type
   * @return diff3Type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDiff3Type() {
    return diff3Type;
  }

  public void setDiff3Type(String diff3Type) {
    this.diff3Type = diff3Type;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem diff4(String diff4) {
    this.diff4 = diff4;
    return this;
  }

   /**
   * Get diff4
   * @return diff4
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDiff4() {
    return diff4;
  }

  public void setDiff4(String diff4) {
    this.diff4 = diff4;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem diff4Type(String diff4Type) {
    this.diff4Type = diff4Type;
    return this;
  }

   /**
   * Get diff4Type
   * @return diff4Type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDiff4Type() {
    return diff4Type;
  }

  public void setDiff4Type(String diff4Type) {
    this.diff4Type = diff4Type;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem departmentId(Long departmentId) {
    this.departmentId = departmentId;
    return this;
  }

   /**
   * Get departmentId
   * @return departmentId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDepartmentId() {
    return departmentId;
  }

  public void setDepartmentId(Long departmentId) {
    this.departmentId = departmentId;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem departmentName(String departmentName) {
    this.departmentName = departmentName;
    return this;
  }

   /**
   * Get departmentName
   * @return departmentName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDepartmentName() {
    return departmentName;
  }

  public void setDepartmentName(String departmentName) {
    this.departmentName = departmentName;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem classId(String classId) {
    this.classId = classId;
    return this;
  }

   /**
   * Get classId
   * @return classId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getClassId() {
    return classId;
  }

  public void setClassId(String classId) {
    this.classId = classId;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem className(String className) {
    this.className = className;
    return this;
  }

   /**
   * Get className
   * @return className
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getClassName() {
    return className;
  }

  public void setClassName(String className) {
    this.className = className;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem subclassId(String subclassId) {
    this.subclassId = subclassId;
    return this;
  }

   /**
   * Get subclassId
   * @return subclassId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getSubclassId() {
    return subclassId;
  }

  public void setSubclassId(String subclassId) {
    this.subclassId = subclassId;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem subclassName(String subclassName) {
    this.subclassName = subclassName;
    return this;
  }

   /**
   * Get subclassName
   * @return subclassName
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getSubclassName() {
    return subclassName;
  }

  public void setSubclassName(String subclassName) {
    this.subclassName = subclassName;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem longDescription(String longDescription) {
    this.longDescription = longDescription;
    return this;
  }

   /**
   * Get longDescription
   * @return longDescription
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getLongDescription() {
    return longDescription;
  }

  public void setLongDescription(String longDescription) {
    this.longDescription = longDescription;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem shortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
    return this;
  }

   /**
   * Get shortDescription
   * @return shortDescription
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getShortDescription() {
    return shortDescription;
  }

  public void setShortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem uppercaseLongDescription(String uppercaseLongDescription) {
    this.uppercaseLongDescription = uppercaseLongDescription;
    return this;
  }

   /**
   * Get uppercaseLongDescription
   * @return uppercaseLongDescription
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getUppercaseLongDescription() {
    return uppercaseLongDescription;
  }

  public void setUppercaseLongDescription(String uppercaseLongDescription) {
    this.uppercaseLongDescription = uppercaseLongDescription;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem isSKUPrimaryBarcode(String isSKUPrimaryBarcode) {
    this.isSKUPrimaryBarcode = isSKUPrimaryBarcode;
    return this;
  }

   /**
   * Get isSKUPrimaryBarcode
   * @return isSKUPrimaryBarcode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIsSKUPrimaryBarcode() {
    return isSKUPrimaryBarcode;
  }

  public void setIsSKUPrimaryBarcode(String isSKUPrimaryBarcode) {
    this.isSKUPrimaryBarcode = isSKUPrimaryBarcode;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem standardUom(String standardUom) {
    this.standardUom = standardUom;
    return this;
  }

   /**
   * Get standardUom
   * @return standardUom
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getStandardUom() {
    return standardUom;
  }

  public void setStandardUom(String standardUom) {
    this.standardUom = standardUom;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem uomConvFactor(Double uomConvFactor) {
    this.uomConvFactor = uomConvFactor;
    return this;
  }

   /**
   * Get uomConvFactor
   * @return uomConvFactor
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getUomConvFactor() {
    return uomConvFactor;
  }

  public void setUomConvFactor(Double uomConvFactor) {
    this.uomConvFactor = uomConvFactor;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem forecastInd(String forecastInd) {
    this.forecastInd = forecastInd;
    return this;
  }

   /**
   * Get forecastInd
   * @return forecastInd
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getForecastInd() {
    return forecastInd;
  }

  public void setForecastInd(String forecastInd) {
    this.forecastInd = forecastInd;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem handlingSensitivity(String handlingSensitivity) {
    this.handlingSensitivity = handlingSensitivity;
    return this;
  }

   /**
   * Get handlingSensitivity
   * @return handlingSensitivity
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHandlingSensitivity() {
    return handlingSensitivity;
  }

  public void setHandlingSensitivity(String handlingSensitivity) {
    this.handlingSensitivity = handlingSensitivity;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem handlingSensitivityDesc(String handlingSensitivityDesc) {
    this.handlingSensitivityDesc = handlingSensitivityDesc;
    return this;
  }

   /**
   * Get handlingSensitivityDesc
   * @return handlingSensitivityDesc
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHandlingSensitivityDesc() {
    return handlingSensitivityDesc;
  }

  public void setHandlingSensitivityDesc(String handlingSensitivityDesc) {
    this.handlingSensitivityDesc = handlingSensitivityDesc;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem constDimenInd(String constDimenInd) {
    this.constDimenInd = constDimenInd;
    return this;
  }

   /**
   * Get constDimenInd
   * @return constDimenInd
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getConstDimenInd() {
    return constDimenInd;
  }

  public void setConstDimenInd(String constDimenInd) {
    this.constDimenInd = constDimenInd;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem isSimplePack(String isSimplePack) {
    this.isSimplePack = isSimplePack;
    return this;
  }

   /**
   * Get isSimplePack
   * @return isSimplePack
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getIsSimplePack() {
    return isSimplePack;
  }

  public void setIsSimplePack(String isSimplePack) {
    this.isSimplePack = isSimplePack;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem packContainsInnerPack(String packContainsInnerPack) {
    this.packContainsInnerPack = packContainsInnerPack;
    return this;
  }

   /**
   * Get packContainsInnerPack
   * @return packContainsInnerPack
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getPackContainsInnerPack() {
    return packContainsInnerPack;
  }

  public void setPackContainsInnerPack(String packContainsInnerPack) {
    this.packContainsInnerPack = packContainsInnerPack;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem packIsSellable(String packIsSellable) {
    this.packIsSellable = packIsSellable;
    return this;
  }

   /**
   * Get packIsSellable
   * @return packIsSellable
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getPackIsSellable() {
    return packIsSellable;
  }

  public void setPackIsSellable(String packIsSellable) {
    this.packIsSellable = packIsSellable;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem packIsOrderable(String packIsOrderable) {
    this.packIsOrderable = packIsOrderable;
    return this;
  }

   /**
   * Get packIsOrderable
   * @return packIsOrderable
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getPackIsOrderable() {
    return packIsOrderable;
  }

  public void setPackIsOrderable(String packIsOrderable) {
    this.packIsOrderable = packIsOrderable;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem packType(String packType) {
    this.packType = packType;
    return this;
  }

   /**
   * Get packType
   * @return packType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPackType() {
    return packType;
  }

  public void setPackType(String packType) {
    this.packType = packType;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem orderAsType(String orderAsType) {
    this.orderAsType = orderAsType;
    return this;
  }

   /**
   * Get orderAsType
   * @return orderAsType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOrderAsType() {
    return orderAsType;
  }

  public void setOrderAsType(String orderAsType) {
    this.orderAsType = orderAsType;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem isPerishable(String isPerishable) {
    this.isPerishable = isPerishable;
    return this;
  }

   /**
   * Get isPerishable
   * @return isPerishable
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIsPerishable() {
    return isPerishable;
  }

  public void setIsPerishable(String isPerishable) {
    this.isPerishable = isPerishable;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem inventoryInd(String inventoryInd) {
    this.inventoryInd = inventoryInd;
    return this;
  }

   /**
   * Get inventoryInd
   * @return inventoryInd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInventoryInd() {
    return inventoryInd;
  }

  public void setInventoryInd(String inventoryInd) {
    this.inventoryInd = inventoryInd;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem purchaseType(String purchaseType) {
    this.purchaseType = purchaseType;
    return this;
  }

   /**
   * Get purchaseType
   * @return purchaseType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPurchaseType() {
    return purchaseType;
  }

  public void setPurchaseType(String purchaseType) {
    this.purchaseType = purchaseType;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem created(DateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getCreated() {
    return created;
  }

  public void setCreated(DateTime created) {
    this.created = created;
  }

  public WiggleMerchandisingItemsReaderModelsItemsItem modified(DateTime modified) {
    this.modified = modified;
    return this;
  }

   /**
   * Get modified
   * @return modified
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getModified() {
    return modified;
  }

  public void setModified(DateTime modified) {
    this.modified = modified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WiggleMerchandisingItemsReaderModelsItemsItem wiggleMerchandisingItemsReaderModelsItemsItem = (WiggleMerchandisingItemsReaderModelsItemsItem) o;
    return Objects.equals(this.itemId, wiggleMerchandisingItemsReaderModelsItemsItem.itemId) &&
        Objects.equals(this.itemNumberType, wiggleMerchandisingItemsReaderModelsItemsItem.itemNumberType) &&
        Objects.equals(this.variableUPCFormatId, wiggleMerchandisingItemsReaderModelsItemsItem.variableUPCFormatId) &&
        Objects.equals(this.variableWeightUPCPrefix, wiggleMerchandisingItemsReaderModelsItemsItem.variableWeightUPCPrefix) &&
        Objects.equals(this.itemParentId, wiggleMerchandisingItemsReaderModelsItemsItem.itemParentId) &&
        Objects.equals(this.itemGrandparentId, wiggleMerchandisingItemsReaderModelsItemsItem.itemGrandparentId) &&
        Objects.equals(this.isPack, wiggleMerchandisingItemsReaderModelsItemsItem.isPack) &&
        Objects.equals(this.itemLevel, wiggleMerchandisingItemsReaderModelsItemsItem.itemLevel) &&
        Objects.equals(this.transactionLevel, wiggleMerchandisingItemsReaderModelsItemsItem.transactionLevel) &&
        Objects.equals(this.diff1, wiggleMerchandisingItemsReaderModelsItemsItem.diff1) &&
        Objects.equals(this.diff1Type, wiggleMerchandisingItemsReaderModelsItemsItem.diff1Type) &&
        Objects.equals(this.diff2, wiggleMerchandisingItemsReaderModelsItemsItem.diff2) &&
        Objects.equals(this.diff2Type, wiggleMerchandisingItemsReaderModelsItemsItem.diff2Type) &&
        Objects.equals(this.diff3, wiggleMerchandisingItemsReaderModelsItemsItem.diff3) &&
        Objects.equals(this.diff3Type, wiggleMerchandisingItemsReaderModelsItemsItem.diff3Type) &&
        Objects.equals(this.diff4, wiggleMerchandisingItemsReaderModelsItemsItem.diff4) &&
        Objects.equals(this.diff4Type, wiggleMerchandisingItemsReaderModelsItemsItem.diff4Type) &&
        Objects.equals(this.departmentId, wiggleMerchandisingItemsReaderModelsItemsItem.departmentId) &&
        Objects.equals(this.departmentName, wiggleMerchandisingItemsReaderModelsItemsItem.departmentName) &&
        Objects.equals(this.classId, wiggleMerchandisingItemsReaderModelsItemsItem.classId) &&
        Objects.equals(this.className, wiggleMerchandisingItemsReaderModelsItemsItem.className) &&
        Objects.equals(this.subclassId, wiggleMerchandisingItemsReaderModelsItemsItem.subclassId) &&
        Objects.equals(this.subclassName, wiggleMerchandisingItemsReaderModelsItemsItem.subclassName) &&
        Objects.equals(this.status, wiggleMerchandisingItemsReaderModelsItemsItem.status) &&
        Objects.equals(this.longDescription, wiggleMerchandisingItemsReaderModelsItemsItem.longDescription) &&
        Objects.equals(this.shortDescription, wiggleMerchandisingItemsReaderModelsItemsItem.shortDescription) &&
        Objects.equals(this.uppercaseLongDescription, wiggleMerchandisingItemsReaderModelsItemsItem.uppercaseLongDescription) &&
        Objects.equals(this.isSKUPrimaryBarcode, wiggleMerchandisingItemsReaderModelsItemsItem.isSKUPrimaryBarcode) &&
        Objects.equals(this.standardUom, wiggleMerchandisingItemsReaderModelsItemsItem.standardUom) &&
        Objects.equals(this.uomConvFactor, wiggleMerchandisingItemsReaderModelsItemsItem.uomConvFactor) &&
        Objects.equals(this.forecastInd, wiggleMerchandisingItemsReaderModelsItemsItem.forecastInd) &&
        Objects.equals(this.handlingSensitivity, wiggleMerchandisingItemsReaderModelsItemsItem.handlingSensitivity) &&
        Objects.equals(this.handlingSensitivityDesc, wiggleMerchandisingItemsReaderModelsItemsItem.handlingSensitivityDesc) &&
        Objects.equals(this.constDimenInd, wiggleMerchandisingItemsReaderModelsItemsItem.constDimenInd) &&
        Objects.equals(this.isSimplePack, wiggleMerchandisingItemsReaderModelsItemsItem.isSimplePack) &&
        Objects.equals(this.packContainsInnerPack, wiggleMerchandisingItemsReaderModelsItemsItem.packContainsInnerPack) &&
        Objects.equals(this.packIsSellable, wiggleMerchandisingItemsReaderModelsItemsItem.packIsSellable) &&
        Objects.equals(this.packIsOrderable, wiggleMerchandisingItemsReaderModelsItemsItem.packIsOrderable) &&
        Objects.equals(this.packType, wiggleMerchandisingItemsReaderModelsItemsItem.packType) &&
        Objects.equals(this.orderAsType, wiggleMerchandisingItemsReaderModelsItemsItem.orderAsType) &&
        Objects.equals(this.comments, wiggleMerchandisingItemsReaderModelsItemsItem.comments) &&
        Objects.equals(this.isPerishable, wiggleMerchandisingItemsReaderModelsItemsItem.isPerishable) &&
        Objects.equals(this.inventoryInd, wiggleMerchandisingItemsReaderModelsItemsItem.inventoryInd) &&
        Objects.equals(this.purchaseType, wiggleMerchandisingItemsReaderModelsItemsItem.purchaseType) &&
        Objects.equals(this.created, wiggleMerchandisingItemsReaderModelsItemsItem.created) &&
        Objects.equals(this.modified, wiggleMerchandisingItemsReaderModelsItemsItem.modified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemId, itemNumberType, variableUPCFormatId, variableWeightUPCPrefix, itemParentId, itemGrandparentId, isPack, itemLevel, transactionLevel, diff1, diff1Type, diff2, diff2Type, diff3, diff3Type, diff4, diff4Type, departmentId, departmentName, classId, className, subclassId, subclassName, status, longDescription, shortDescription, uppercaseLongDescription, isSKUPrimaryBarcode, standardUom, uomConvFactor, forecastInd, handlingSensitivity, handlingSensitivityDesc, constDimenInd, isSimplePack, packContainsInnerPack, packIsSellable, packIsOrderable, packType, orderAsType, comments, isPerishable, inventoryInd, purchaseType, created, modified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WiggleMerchandisingItemsReaderModelsItemsItem {\n");
    
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    itemNumberType: ").append(toIndentedString(itemNumberType)).append("\n");
    sb.append("    variableUPCFormatId: ").append(toIndentedString(variableUPCFormatId)).append("\n");
    sb.append("    variableWeightUPCPrefix: ").append(toIndentedString(variableWeightUPCPrefix)).append("\n");
    sb.append("    itemParentId: ").append(toIndentedString(itemParentId)).append("\n");
    sb.append("    itemGrandparentId: ").append(toIndentedString(itemGrandparentId)).append("\n");
    sb.append("    isPack: ").append(toIndentedString(isPack)).append("\n");
    sb.append("    itemLevel: ").append(toIndentedString(itemLevel)).append("\n");
    sb.append("    transactionLevel: ").append(toIndentedString(transactionLevel)).append("\n");
    sb.append("    diff1: ").append(toIndentedString(diff1)).append("\n");
    sb.append("    diff1Type: ").append(toIndentedString(diff1Type)).append("\n");
    sb.append("    diff2: ").append(toIndentedString(diff2)).append("\n");
    sb.append("    diff2Type: ").append(toIndentedString(diff2Type)).append("\n");
    sb.append("    diff3: ").append(toIndentedString(diff3)).append("\n");
    sb.append("    diff3Type: ").append(toIndentedString(diff3Type)).append("\n");
    sb.append("    diff4: ").append(toIndentedString(diff4)).append("\n");
    sb.append("    diff4Type: ").append(toIndentedString(diff4Type)).append("\n");
    sb.append("    departmentId: ").append(toIndentedString(departmentId)).append("\n");
    sb.append("    departmentName: ").append(toIndentedString(departmentName)).append("\n");
    sb.append("    classId: ").append(toIndentedString(classId)).append("\n");
    sb.append("    className: ").append(toIndentedString(className)).append("\n");
    sb.append("    subclassId: ").append(toIndentedString(subclassId)).append("\n");
    sb.append("    subclassName: ").append(toIndentedString(subclassName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    longDescription: ").append(toIndentedString(longDescription)).append("\n");
    sb.append("    shortDescription: ").append(toIndentedString(shortDescription)).append("\n");
    sb.append("    uppercaseLongDescription: ").append(toIndentedString(uppercaseLongDescription)).append("\n");
    sb.append("    isSKUPrimaryBarcode: ").append(toIndentedString(isSKUPrimaryBarcode)).append("\n");
    sb.append("    standardUom: ").append(toIndentedString(standardUom)).append("\n");
    sb.append("    uomConvFactor: ").append(toIndentedString(uomConvFactor)).append("\n");
    sb.append("    forecastInd: ").append(toIndentedString(forecastInd)).append("\n");
    sb.append("    handlingSensitivity: ").append(toIndentedString(handlingSensitivity)).append("\n");
    sb.append("    handlingSensitivityDesc: ").append(toIndentedString(handlingSensitivityDesc)).append("\n");
    sb.append("    constDimenInd: ").append(toIndentedString(constDimenInd)).append("\n");
    sb.append("    isSimplePack: ").append(toIndentedString(isSimplePack)).append("\n");
    sb.append("    packContainsInnerPack: ").append(toIndentedString(packContainsInnerPack)).append("\n");
    sb.append("    packIsSellable: ").append(toIndentedString(packIsSellable)).append("\n");
    sb.append("    packIsOrderable: ").append(toIndentedString(packIsOrderable)).append("\n");
    sb.append("    packType: ").append(toIndentedString(packType)).append("\n");
    sb.append("    orderAsType: ").append(toIndentedString(orderAsType)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    isPerishable: ").append(toIndentedString(isPerishable)).append("\n");
    sb.append("    inventoryInd: ").append(toIndentedString(inventoryInd)).append("\n");
    sb.append("    purchaseType: ").append(toIndentedString(purchaseType)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

