/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Apiv1crcordersBankTransfer;
import io.swagger.client.model.Apiv1crcordersBraintree;
import io.swagger.client.model.Apiv1crcordersChequeCashDraft;
import io.swagger.client.model.Apiv1crcordersCreditCard;
import io.swagger.client.model.Apiv1crcordersFinance;
import io.swagger.client.model.Apiv1crcordersFreeOfCharge;
import io.swagger.client.model.Apiv1crcordersGiftCertificates;
import io.swagger.client.model.Apiv1crcordersOnAccount;
import io.swagger.client.model.Apiv1crcordersPayPal;
import java.util.ArrayList;
import java.util.List;

/**
 * WiggleCRCModelsATGOrderCreationOrderPaymentType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
public class WiggleCRCModelsATGOrderCreationOrderPaymentType {
  @SerializedName("CreditCard")
  private Apiv1crcordersCreditCard creditCard = null;

  @SerializedName("BankTransfer")
  private Apiv1crcordersBankTransfer bankTransfer = null;

  @SerializedName("PayPal")
  private Apiv1crcordersPayPal payPal = null;

  @SerializedName("GiftCertificates")
  private List<Apiv1crcordersGiftCertificates> giftCertificates = new ArrayList<Apiv1crcordersGiftCertificates>();

  @SerializedName("Braintree")
  private Apiv1crcordersBraintree braintree = null;

  @SerializedName("Finance")
  private Apiv1crcordersFinance finance = null;

  @SerializedName("CycleScheme")
  private Apiv1crcordersFinance cycleScheme = null;

  @SerializedName("FreeOfCharge")
  private Apiv1crcordersFreeOfCharge freeOfCharge = null;

  @SerializedName("OnAccount")
  private Apiv1crcordersOnAccount onAccount = null;

  @SerializedName("ChequeCashDraft")
  private Apiv1crcordersChequeCashDraft chequeCashDraft = null;

  public WiggleCRCModelsATGOrderCreationOrderPaymentType creditCard(Apiv1crcordersCreditCard creditCard) {
    this.creditCard = creditCard;
    return this;
  }

   /**
   * Get creditCard
   * @return creditCard
  **/
  @ApiModelProperty(example = "null", value = "")
  public Apiv1crcordersCreditCard getCreditCard() {
    return creditCard;
  }

  public void setCreditCard(Apiv1crcordersCreditCard creditCard) {
    this.creditCard = creditCard;
  }

  public WiggleCRCModelsATGOrderCreationOrderPaymentType bankTransfer(Apiv1crcordersBankTransfer bankTransfer) {
    this.bankTransfer = bankTransfer;
    return this;
  }

   /**
   * Get bankTransfer
   * @return bankTransfer
  **/
  @ApiModelProperty(example = "null", value = "")
  public Apiv1crcordersBankTransfer getBankTransfer() {
    return bankTransfer;
  }

  public void setBankTransfer(Apiv1crcordersBankTransfer bankTransfer) {
    this.bankTransfer = bankTransfer;
  }

  public WiggleCRCModelsATGOrderCreationOrderPaymentType payPal(Apiv1crcordersPayPal payPal) {
    this.payPal = payPal;
    return this;
  }

   /**
   * Get payPal
   * @return payPal
  **/
  @ApiModelProperty(example = "null", value = "")
  public Apiv1crcordersPayPal getPayPal() {
    return payPal;
  }

  public void setPayPal(Apiv1crcordersPayPal payPal) {
    this.payPal = payPal;
  }

  public WiggleCRCModelsATGOrderCreationOrderPaymentType giftCertificates(List<Apiv1crcordersGiftCertificates> giftCertificates) {
    this.giftCertificates = giftCertificates;
    return this;
  }

  public WiggleCRCModelsATGOrderCreationOrderPaymentType addGiftCertificatesItem(Apiv1crcordersGiftCertificates giftCertificatesItem) {
    this.giftCertificates.add(giftCertificatesItem);
    return this;
  }

   /**
   * Get giftCertificates
   * @return giftCertificates
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Apiv1crcordersGiftCertificates> getGiftCertificates() {
    return giftCertificates;
  }

  public void setGiftCertificates(List<Apiv1crcordersGiftCertificates> giftCertificates) {
    this.giftCertificates = giftCertificates;
  }

  public WiggleCRCModelsATGOrderCreationOrderPaymentType braintree(Apiv1crcordersBraintree braintree) {
    this.braintree = braintree;
    return this;
  }

   /**
   * Get braintree
   * @return braintree
  **/
  @ApiModelProperty(example = "null", value = "")
  public Apiv1crcordersBraintree getBraintree() {
    return braintree;
  }

  public void setBraintree(Apiv1crcordersBraintree braintree) {
    this.braintree = braintree;
  }

  public WiggleCRCModelsATGOrderCreationOrderPaymentType finance(Apiv1crcordersFinance finance) {
    this.finance = finance;
    return this;
  }

   /**
   * Get finance
   * @return finance
  **/
  @ApiModelProperty(example = "null", value = "")
  public Apiv1crcordersFinance getFinance() {
    return finance;
  }

  public void setFinance(Apiv1crcordersFinance finance) {
    this.finance = finance;
  }

  public WiggleCRCModelsATGOrderCreationOrderPaymentType cycleScheme(Apiv1crcordersFinance cycleScheme) {
    this.cycleScheme = cycleScheme;
    return this;
  }

   /**
   * Get cycleScheme
   * @return cycleScheme
  **/
  @ApiModelProperty(example = "null", value = "")
  public Apiv1crcordersFinance getCycleScheme() {
    return cycleScheme;
  }

  public void setCycleScheme(Apiv1crcordersFinance cycleScheme) {
    this.cycleScheme = cycleScheme;
  }

  public WiggleCRCModelsATGOrderCreationOrderPaymentType freeOfCharge(Apiv1crcordersFreeOfCharge freeOfCharge) {
    this.freeOfCharge = freeOfCharge;
    return this;
  }

   /**
   * Get freeOfCharge
   * @return freeOfCharge
  **/
  @ApiModelProperty(example = "null", value = "")
  public Apiv1crcordersFreeOfCharge getFreeOfCharge() {
    return freeOfCharge;
  }

  public void setFreeOfCharge(Apiv1crcordersFreeOfCharge freeOfCharge) {
    this.freeOfCharge = freeOfCharge;
  }

  public WiggleCRCModelsATGOrderCreationOrderPaymentType onAccount(Apiv1crcordersOnAccount onAccount) {
    this.onAccount = onAccount;
    return this;
  }

   /**
   * Get onAccount
   * @return onAccount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Apiv1crcordersOnAccount getOnAccount() {
    return onAccount;
  }

  public void setOnAccount(Apiv1crcordersOnAccount onAccount) {
    this.onAccount = onAccount;
  }

  public WiggleCRCModelsATGOrderCreationOrderPaymentType chequeCashDraft(Apiv1crcordersChequeCashDraft chequeCashDraft) {
    this.chequeCashDraft = chequeCashDraft;
    return this;
  }

   /**
   * Get chequeCashDraft
   * @return chequeCashDraft
  **/
  @ApiModelProperty(example = "null", value = "")
  public Apiv1crcordersChequeCashDraft getChequeCashDraft() {
    return chequeCashDraft;
  }

  public void setChequeCashDraft(Apiv1crcordersChequeCashDraft chequeCashDraft) {
    this.chequeCashDraft = chequeCashDraft;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WiggleCRCModelsATGOrderCreationOrderPaymentType wiggleCRCModelsATGOrderCreationOrderPaymentType = (WiggleCRCModelsATGOrderCreationOrderPaymentType) o;
    return Objects.equals(this.creditCard, wiggleCRCModelsATGOrderCreationOrderPaymentType.creditCard) &&
        Objects.equals(this.bankTransfer, wiggleCRCModelsATGOrderCreationOrderPaymentType.bankTransfer) &&
        Objects.equals(this.payPal, wiggleCRCModelsATGOrderCreationOrderPaymentType.payPal) &&
        Objects.equals(this.giftCertificates, wiggleCRCModelsATGOrderCreationOrderPaymentType.giftCertificates) &&
        Objects.equals(this.braintree, wiggleCRCModelsATGOrderCreationOrderPaymentType.braintree) &&
        Objects.equals(this.finance, wiggleCRCModelsATGOrderCreationOrderPaymentType.finance) &&
        Objects.equals(this.cycleScheme, wiggleCRCModelsATGOrderCreationOrderPaymentType.cycleScheme) &&
        Objects.equals(this.freeOfCharge, wiggleCRCModelsATGOrderCreationOrderPaymentType.freeOfCharge) &&
        Objects.equals(this.onAccount, wiggleCRCModelsATGOrderCreationOrderPaymentType.onAccount) &&
        Objects.equals(this.chequeCashDraft, wiggleCRCModelsATGOrderCreationOrderPaymentType.chequeCashDraft);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creditCard, bankTransfer, payPal, giftCertificates, braintree, finance, cycleScheme, freeOfCharge, onAccount, chequeCashDraft);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WiggleCRCModelsATGOrderCreationOrderPaymentType {\n");
    
    sb.append("    creditCard: ").append(toIndentedString(creditCard)).append("\n");
    sb.append("    bankTransfer: ").append(toIndentedString(bankTransfer)).append("\n");
    sb.append("    payPal: ").append(toIndentedString(payPal)).append("\n");
    sb.append("    giftCertificates: ").append(toIndentedString(giftCertificates)).append("\n");
    sb.append("    braintree: ").append(toIndentedString(braintree)).append("\n");
    sb.append("    finance: ").append(toIndentedString(finance)).append("\n");
    sb.append("    cycleScheme: ").append(toIndentedString(cycleScheme)).append("\n");
    sb.append("    freeOfCharge: ").append(toIndentedString(freeOfCharge)).append("\n");
    sb.append("    onAccount: ").append(toIndentedString(onAccount)).append("\n");
    sb.append("    chequeCashDraft: ").append(toIndentedString(chequeCashDraft)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

