/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse2003LineItems;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
public class WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent {
  @SerializedName("SequenceId")
  private Long sequenceId = null;

  @SerializedName("TimeStamp")
  private Long timeStamp = null;

  @SerializedName("ReferenceId")
  private String referenceId = null;

  @SerializedName("StatusCode")
  private String statusCode = null;

  @SerializedName("Status")
  private String status = null;

  @SerializedName("TransactionDate")
  private DateTime transactionDate = null;

  @SerializedName("Notes")
  private String notes = null;

  @SerializedName("TrackingNumber")
  private String trackingNumber = null;

  @SerializedName("ShippingMethod")
  private String shippingMethod = null;

  @SerializedName("Carrier")
  private String carrier = null;

  @SerializedName("TrackingURL")
  private String trackingURL = null;

  @SerializedName("LineItems")
  private List<InlineResponse2003LineItems> lineItems = new ArrayList<InlineResponse2003LineItems>();

  public WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent sequenceId(Long sequenceId) {
    this.sequenceId = sequenceId;
    return this;
  }

   /**
   * Get sequenceId
   * @return sequenceId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSequenceId() {
    return sequenceId;
  }

  public void setSequenceId(Long sequenceId) {
    this.sequenceId = sequenceId;
  }

  public WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent timeStamp(Long timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * Get timeStamp
   * @return timeStamp
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTimeStamp() {
    return timeStamp;
  }

  public void setTimeStamp(Long timeStamp) {
    this.timeStamp = timeStamp;
  }

  public WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent referenceId(String referenceId) {
    this.referenceId = referenceId;
    return this;
  }

   /**
   * Get referenceId
   * @return referenceId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReferenceId() {
    return referenceId;
  }

  public void setReferenceId(String referenceId) {
    this.referenceId = referenceId;
  }

  public WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent statusCode(String statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Get statusCode
   * @return statusCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(String statusCode) {
    this.statusCode = statusCode;
  }

  public WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent transactionDate(DateTime transactionDate) {
    this.transactionDate = transactionDate;
    return this;
  }

   /**
   * Get transactionDate
   * @return transactionDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getTransactionDate() {
    return transactionDate;
  }

  public void setTransactionDate(DateTime transactionDate) {
    this.transactionDate = transactionDate;
  }

  public WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent trackingNumber(String trackingNumber) {
    this.trackingNumber = trackingNumber;
    return this;
  }

   /**
   * Get trackingNumber
   * @return trackingNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTrackingNumber() {
    return trackingNumber;
  }

  public void setTrackingNumber(String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }

  public WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent shippingMethod(String shippingMethod) {
    this.shippingMethod = shippingMethod;
    return this;
  }

   /**
   * Get shippingMethod
   * @return shippingMethod
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getShippingMethod() {
    return shippingMethod;
  }

  public void setShippingMethod(String shippingMethod) {
    this.shippingMethod = shippingMethod;
  }

  public WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent carrier(String carrier) {
    this.carrier = carrier;
    return this;
  }

   /**
   * Get carrier
   * @return carrier
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCarrier() {
    return carrier;
  }

  public void setCarrier(String carrier) {
    this.carrier = carrier;
  }

  public WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent trackingURL(String trackingURL) {
    this.trackingURL = trackingURL;
    return this;
  }

   /**
   * Get trackingURL
   * @return trackingURL
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTrackingURL() {
    return trackingURL;
  }

  public void setTrackingURL(String trackingURL) {
    this.trackingURL = trackingURL;
  }

  public WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent lineItems(List<InlineResponse2003LineItems> lineItems) {
    this.lineItems = lineItems;
    return this;
  }

  public WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent addLineItemsItem(InlineResponse2003LineItems lineItemsItem) {
    this.lineItems.add(lineItemsItem);
    return this;
  }

   /**
   * Get lineItems
   * @return lineItems
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<InlineResponse2003LineItems> getLineItems() {
    return lineItems;
  }

  public void setLineItems(List<InlineResponse2003LineItems> lineItems) {
    this.lineItems = lineItems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent wiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent = (WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent) o;
    return Objects.equals(this.sequenceId, wiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent.sequenceId) &&
        Objects.equals(this.timeStamp, wiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent.timeStamp) &&
        Objects.equals(this.referenceId, wiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent.referenceId) &&
        Objects.equals(this.statusCode, wiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent.statusCode) &&
        Objects.equals(this.status, wiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent.status) &&
        Objects.equals(this.transactionDate, wiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent.transactionDate) &&
        Objects.equals(this.notes, wiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent.notes) &&
        Objects.equals(this.trackingNumber, wiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent.trackingNumber) &&
        Objects.equals(this.shippingMethod, wiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent.shippingMethod) &&
        Objects.equals(this.carrier, wiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent.carrier) &&
        Objects.equals(this.trackingURL, wiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent.trackingURL) &&
        Objects.equals(this.lineItems, wiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent.lineItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sequenceId, timeStamp, referenceId, statusCode, status, transactionDate, notes, trackingNumber, shippingMethod, carrier, trackingURL, lineItems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WiggleDataPortalsCRCCommonContractsDTOOrderEventsOrderEvent {\n");
    
    sb.append("    sequenceId: ").append(toIndentedString(sequenceId)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("    referenceId: ").append(toIndentedString(referenceId)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    transactionDate: ").append(toIndentedString(transactionDate)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    trackingNumber: ").append(toIndentedString(trackingNumber)).append("\n");
    sb.append("    shippingMethod: ").append(toIndentedString(shippingMethod)).append("\n");
    sb.append("    carrier: ").append(toIndentedString(carrier)).append("\n");
    sb.append("    trackingURL: ").append(toIndentedString(trackingURL)).append("\n");
    sb.append("    lineItems: ").append(toIndentedString(lineItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

