/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Apiv1crcordersBraintreeBraintreeCard;
import io.swagger.client.model.Apiv1crcordersBraintreeBraintreeFraudIndicators;
import io.swagger.client.model.Apiv1crcordersBraintreeTransaction;

/**
 * WiggleCRCModelsATGOrderCreationPaymentTypesBraintreePaymentBraintree
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
public class WiggleCRCModelsATGOrderCreationPaymentTypesBraintreePaymentBraintree {
  @SerializedName("Transaction")
  private Apiv1crcordersBraintreeTransaction transaction = null;

  @SerializedName("BraintreeCard")
  private Apiv1crcordersBraintreeBraintreeCard braintreeCard = null;

  @SerializedName("BraintreeFraudIndicators")
  private Apiv1crcordersBraintreeBraintreeFraudIndicators braintreeFraudIndicators = null;

  public WiggleCRCModelsATGOrderCreationPaymentTypesBraintreePaymentBraintree transaction(Apiv1crcordersBraintreeTransaction transaction) {
    this.transaction = transaction;
    return this;
  }

   /**
   * Get transaction
   * @return transaction
  **/
  @ApiModelProperty(example = "null", value = "")
  public Apiv1crcordersBraintreeTransaction getTransaction() {
    return transaction;
  }

  public void setTransaction(Apiv1crcordersBraintreeTransaction transaction) {
    this.transaction = transaction;
  }

  public WiggleCRCModelsATGOrderCreationPaymentTypesBraintreePaymentBraintree braintreeCard(Apiv1crcordersBraintreeBraintreeCard braintreeCard) {
    this.braintreeCard = braintreeCard;
    return this;
  }

   /**
   * Get braintreeCard
   * @return braintreeCard
  **/
  @ApiModelProperty(example = "null", value = "")
  public Apiv1crcordersBraintreeBraintreeCard getBraintreeCard() {
    return braintreeCard;
  }

  public void setBraintreeCard(Apiv1crcordersBraintreeBraintreeCard braintreeCard) {
    this.braintreeCard = braintreeCard;
  }

  public WiggleCRCModelsATGOrderCreationPaymentTypesBraintreePaymentBraintree braintreeFraudIndicators(Apiv1crcordersBraintreeBraintreeFraudIndicators braintreeFraudIndicators) {
    this.braintreeFraudIndicators = braintreeFraudIndicators;
    return this;
  }

   /**
   * Get braintreeFraudIndicators
   * @return braintreeFraudIndicators
  **/
  @ApiModelProperty(example = "null", value = "")
  public Apiv1crcordersBraintreeBraintreeFraudIndicators getBraintreeFraudIndicators() {
    return braintreeFraudIndicators;
  }

  public void setBraintreeFraudIndicators(Apiv1crcordersBraintreeBraintreeFraudIndicators braintreeFraudIndicators) {
    this.braintreeFraudIndicators = braintreeFraudIndicators;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WiggleCRCModelsATGOrderCreationPaymentTypesBraintreePaymentBraintree wiggleCRCModelsATGOrderCreationPaymentTypesBraintreePaymentBraintree = (WiggleCRCModelsATGOrderCreationPaymentTypesBraintreePaymentBraintree) o;
    return Objects.equals(this.transaction, wiggleCRCModelsATGOrderCreationPaymentTypesBraintreePaymentBraintree.transaction) &&
        Objects.equals(this.braintreeCard, wiggleCRCModelsATGOrderCreationPaymentTypesBraintreePaymentBraintree.braintreeCard) &&
        Objects.equals(this.braintreeFraudIndicators, wiggleCRCModelsATGOrderCreationPaymentTypesBraintreePaymentBraintree.braintreeFraudIndicators);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transaction, braintreeCard, braintreeFraudIndicators);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WiggleCRCModelsATGOrderCreationPaymentTypesBraintreePaymentBraintree {\n");
    
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("    braintreeCard: ").append(toIndentedString(braintreeCard)).append("\n");
    sb.append("    braintreeFraudIndicators: ").append(toIndentedString(braintreeFraudIndicators)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

