/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * WiggleCRCModelsATGOrderCreationOrderShippingAddress
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
public class WiggleCRCModelsATGOrderCreationOrderShippingAddress {
  @SerializedName("CollectionPointId")
  private String collectionPointId = null;

  @SerializedName("MobileNumber")
  private String mobileNumber = null;

  @SerializedName("FirstName")
  private String firstName = null;

  @SerializedName("Surname")
  private String surname = null;

  @SerializedName("AddressLine1")
  private String addressLine1 = null;

  @SerializedName("AddressLine2")
  private String addressLine2 = null;

  @SerializedName("City")
  private String city = null;

  @SerializedName("County")
  private String county = null;

  @SerializedName("Country")
  private String country = null;

  @SerializedName("PostCode")
  private String postCode = null;

  public WiggleCRCModelsATGOrderCreationOrderShippingAddress collectionPointId(String collectionPointId) {
    this.collectionPointId = collectionPointId;
    return this;
  }

   /**
   * Get collectionPointId
   * @return collectionPointId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCollectionPointId() {
    return collectionPointId;
  }

  public void setCollectionPointId(String collectionPointId) {
    this.collectionPointId = collectionPointId;
  }

  public WiggleCRCModelsATGOrderCreationOrderShippingAddress mobileNumber(String mobileNumber) {
    this.mobileNumber = mobileNumber;
    return this;
  }

   /**
   * Get mobileNumber
   * @return mobileNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMobileNumber() {
    return mobileNumber;
  }

  public void setMobileNumber(String mobileNumber) {
    this.mobileNumber = mobileNumber;
  }

  public WiggleCRCModelsATGOrderCreationOrderShippingAddress firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public WiggleCRCModelsATGOrderCreationOrderShippingAddress surname(String surname) {
    this.surname = surname;
    return this;
  }

   /**
   * Get surname
   * @return surname
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSurname() {
    return surname;
  }

  public void setSurname(String surname) {
    this.surname = surname;
  }

  public WiggleCRCModelsATGOrderCreationOrderShippingAddress addressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
    return this;
  }

   /**
   * Get addressLine1
   * @return addressLine1
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAddressLine1() {
    return addressLine1;
  }

  public void setAddressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
  }

  public WiggleCRCModelsATGOrderCreationOrderShippingAddress addressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
    return this;
  }

   /**
   * Get addressLine2
   * @return addressLine2
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAddressLine2() {
    return addressLine2;
  }

  public void setAddressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
  }

  public WiggleCRCModelsATGOrderCreationOrderShippingAddress city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public WiggleCRCModelsATGOrderCreationOrderShippingAddress county(String county) {
    this.county = county;
    return this;
  }

   /**
   * Get county
   * @return county
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCounty() {
    return county;
  }

  public void setCounty(String county) {
    this.county = county;
  }

  public WiggleCRCModelsATGOrderCreationOrderShippingAddress country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public WiggleCRCModelsATGOrderCreationOrderShippingAddress postCode(String postCode) {
    this.postCode = postCode;
    return this;
  }

   /**
   * Get postCode
   * @return postCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPostCode() {
    return postCode;
  }

  public void setPostCode(String postCode) {
    this.postCode = postCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WiggleCRCModelsATGOrderCreationOrderShippingAddress wiggleCRCModelsATGOrderCreationOrderShippingAddress = (WiggleCRCModelsATGOrderCreationOrderShippingAddress) o;
    return Objects.equals(this.collectionPointId, wiggleCRCModelsATGOrderCreationOrderShippingAddress.collectionPointId) &&
        Objects.equals(this.mobileNumber, wiggleCRCModelsATGOrderCreationOrderShippingAddress.mobileNumber) &&
        Objects.equals(this.firstName, wiggleCRCModelsATGOrderCreationOrderShippingAddress.firstName) &&
        Objects.equals(this.surname, wiggleCRCModelsATGOrderCreationOrderShippingAddress.surname) &&
        Objects.equals(this.addressLine1, wiggleCRCModelsATGOrderCreationOrderShippingAddress.addressLine1) &&
        Objects.equals(this.addressLine2, wiggleCRCModelsATGOrderCreationOrderShippingAddress.addressLine2) &&
        Objects.equals(this.city, wiggleCRCModelsATGOrderCreationOrderShippingAddress.city) &&
        Objects.equals(this.county, wiggleCRCModelsATGOrderCreationOrderShippingAddress.county) &&
        Objects.equals(this.country, wiggleCRCModelsATGOrderCreationOrderShippingAddress.country) &&
        Objects.equals(this.postCode, wiggleCRCModelsATGOrderCreationOrderShippingAddress.postCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collectionPointId, mobileNumber, firstName, surname, addressLine1, addressLine2, city, county, country, postCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WiggleCRCModelsATGOrderCreationOrderShippingAddress {\n");
    
    sb.append("    collectionPointId: ").append(toIndentedString(collectionPointId)).append("\n");
    sb.append("    mobileNumber: ").append(toIndentedString(mobileNumber)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    county: ").append(toIndentedString(county)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    postCode: ").append(toIndentedString(postCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

