/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * WiggleCRCModelsATGOrderCreationItemOrderItemKitItem
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-22T10:29:28.037Z")
public class WiggleCRCModelsATGOrderCreationItemOrderItemKitItem {
  @SerializedName("ReferenceLineId")
  private String referenceLineId = null;

  @SerializedName("GroupStockId")
  private String groupStockId = null;

  @SerializedName("Quantity")
  private Integer quantity = null;

  @SerializedName("UnitPrice")
  private Double unitPrice = null;

  @SerializedName("TotalPrice")
  private Double totalPrice = null;

  @SerializedName("PriceBeforeDiscount")
  private Double priceBeforeDiscount = null;

  @SerializedName("UnitCostExVAT")
  private Double unitCostExVAT = null;

  @SerializedName("CountryVATRate")
  private Double countryVATRate = null;

  @SerializedName("UnitVATAmt")
  private Double unitVATAmt = null;

  @SerializedName("TotalItemCostExVAT")
  private Double totalItemCostExVAT = null;

  @SerializedName("TotalItemVAT")
  private Double totalItemVAT = null;

  public WiggleCRCModelsATGOrderCreationItemOrderItemKitItem referenceLineId(String referenceLineId) {
    this.referenceLineId = referenceLineId;
    return this;
  }

   /**
   * Get referenceLineId
   * @return referenceLineId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReferenceLineId() {
    return referenceLineId;
  }

  public void setReferenceLineId(String referenceLineId) {
    this.referenceLineId = referenceLineId;
  }

  public WiggleCRCModelsATGOrderCreationItemOrderItemKitItem groupStockId(String groupStockId) {
    this.groupStockId = groupStockId;
    return this;
  }

   /**
   * Get groupStockId
   * @return groupStockId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGroupStockId() {
    return groupStockId;
  }

  public void setGroupStockId(String groupStockId) {
    this.groupStockId = groupStockId;
  }

  public WiggleCRCModelsATGOrderCreationItemOrderItemKitItem quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public WiggleCRCModelsATGOrderCreationItemOrderItemKitItem unitPrice(Double unitPrice) {
    this.unitPrice = unitPrice;
    return this;
  }

   /**
   * Get unitPrice
   * @return unitPrice
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getUnitPrice() {
    return unitPrice;
  }

  public void setUnitPrice(Double unitPrice) {
    this.unitPrice = unitPrice;
  }

  public WiggleCRCModelsATGOrderCreationItemOrderItemKitItem totalPrice(Double totalPrice) {
    this.totalPrice = totalPrice;
    return this;
  }

   /**
   * Get totalPrice
   * @return totalPrice
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getTotalPrice() {
    return totalPrice;
  }

  public void setTotalPrice(Double totalPrice) {
    this.totalPrice = totalPrice;
  }

  public WiggleCRCModelsATGOrderCreationItemOrderItemKitItem priceBeforeDiscount(Double priceBeforeDiscount) {
    this.priceBeforeDiscount = priceBeforeDiscount;
    return this;
  }

   /**
   * Get priceBeforeDiscount
   * @return priceBeforeDiscount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getPriceBeforeDiscount() {
    return priceBeforeDiscount;
  }

  public void setPriceBeforeDiscount(Double priceBeforeDiscount) {
    this.priceBeforeDiscount = priceBeforeDiscount;
  }

  public WiggleCRCModelsATGOrderCreationItemOrderItemKitItem unitCostExVAT(Double unitCostExVAT) {
    this.unitCostExVAT = unitCostExVAT;
    return this;
  }

   /**
   * Get unitCostExVAT
   * @return unitCostExVAT
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getUnitCostExVAT() {
    return unitCostExVAT;
  }

  public void setUnitCostExVAT(Double unitCostExVAT) {
    this.unitCostExVAT = unitCostExVAT;
  }

  public WiggleCRCModelsATGOrderCreationItemOrderItemKitItem countryVATRate(Double countryVATRate) {
    this.countryVATRate = countryVATRate;
    return this;
  }

   /**
   * Get countryVATRate
   * @return countryVATRate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getCountryVATRate() {
    return countryVATRate;
  }

  public void setCountryVATRate(Double countryVATRate) {
    this.countryVATRate = countryVATRate;
  }

  public WiggleCRCModelsATGOrderCreationItemOrderItemKitItem unitVATAmt(Double unitVATAmt) {
    this.unitVATAmt = unitVATAmt;
    return this;
  }

   /**
   * Get unitVATAmt
   * @return unitVATAmt
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getUnitVATAmt() {
    return unitVATAmt;
  }

  public void setUnitVATAmt(Double unitVATAmt) {
    this.unitVATAmt = unitVATAmt;
  }

  public WiggleCRCModelsATGOrderCreationItemOrderItemKitItem totalItemCostExVAT(Double totalItemCostExVAT) {
    this.totalItemCostExVAT = totalItemCostExVAT;
    return this;
  }

   /**
   * Get totalItemCostExVAT
   * @return totalItemCostExVAT
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getTotalItemCostExVAT() {
    return totalItemCostExVAT;
  }

  public void setTotalItemCostExVAT(Double totalItemCostExVAT) {
    this.totalItemCostExVAT = totalItemCostExVAT;
  }

  public WiggleCRCModelsATGOrderCreationItemOrderItemKitItem totalItemVAT(Double totalItemVAT) {
    this.totalItemVAT = totalItemVAT;
    return this;
  }

   /**
   * Get totalItemVAT
   * @return totalItemVAT
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getTotalItemVAT() {
    return totalItemVAT;
  }

  public void setTotalItemVAT(Double totalItemVAT) {
    this.totalItemVAT = totalItemVAT;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WiggleCRCModelsATGOrderCreationItemOrderItemKitItem wiggleCRCModelsATGOrderCreationItemOrderItemKitItem = (WiggleCRCModelsATGOrderCreationItemOrderItemKitItem) o;
    return Objects.equals(this.referenceLineId, wiggleCRCModelsATGOrderCreationItemOrderItemKitItem.referenceLineId) &&
        Objects.equals(this.groupStockId, wiggleCRCModelsATGOrderCreationItemOrderItemKitItem.groupStockId) &&
        Objects.equals(this.quantity, wiggleCRCModelsATGOrderCreationItemOrderItemKitItem.quantity) &&
        Objects.equals(this.unitPrice, wiggleCRCModelsATGOrderCreationItemOrderItemKitItem.unitPrice) &&
        Objects.equals(this.totalPrice, wiggleCRCModelsATGOrderCreationItemOrderItemKitItem.totalPrice) &&
        Objects.equals(this.priceBeforeDiscount, wiggleCRCModelsATGOrderCreationItemOrderItemKitItem.priceBeforeDiscount) &&
        Objects.equals(this.unitCostExVAT, wiggleCRCModelsATGOrderCreationItemOrderItemKitItem.unitCostExVAT) &&
        Objects.equals(this.countryVATRate, wiggleCRCModelsATGOrderCreationItemOrderItemKitItem.countryVATRate) &&
        Objects.equals(this.unitVATAmt, wiggleCRCModelsATGOrderCreationItemOrderItemKitItem.unitVATAmt) &&
        Objects.equals(this.totalItemCostExVAT, wiggleCRCModelsATGOrderCreationItemOrderItemKitItem.totalItemCostExVAT) &&
        Objects.equals(this.totalItemVAT, wiggleCRCModelsATGOrderCreationItemOrderItemKitItem.totalItemVAT);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referenceLineId, groupStockId, quantity, unitPrice, totalPrice, priceBeforeDiscount, unitCostExVAT, countryVATRate, unitVATAmt, totalItemCostExVAT, totalItemVAT);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WiggleCRCModelsATGOrderCreationItemOrderItemKitItem {\n");
    
    sb.append("    referenceLineId: ").append(toIndentedString(referenceLineId)).append("\n");
    sb.append("    groupStockId: ").append(toIndentedString(groupStockId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("    priceBeforeDiscount: ").append(toIndentedString(priceBeforeDiscount)).append("\n");
    sb.append("    unitCostExVAT: ").append(toIndentedString(unitCostExVAT)).append("\n");
    sb.append("    countryVATRate: ").append(toIndentedString(countryVATRate)).append("\n");
    sb.append("    unitVATAmt: ").append(toIndentedString(unitVATAmt)).append("\n");
    sb.append("    totalItemCostExVAT: ").append(toIndentedString(totalItemCostExVAT)).append("\n");
    sb.append("    totalItemVAT: ").append(toIndentedString(totalItemVAT)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

