/*
 * Wiggle.DataPortals.CRC.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse2001;
import io.swagger.client.model.InlineResponse400;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AvailibilityApi
 */
@Ignore
public class AvailibilityApiTest {

    private final AvailibilityApi api = new AvailibilityApi();

    
    /**
     * Gets page from availability stream
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void availibilityGetTest() throws ApiException {
        Long from = null;
        Integer take = null;
        InlineResponse2001 response = api.availibilityGet(from, take);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void availibilityGetByProductIdTest() throws ApiException {
        Long id = null;
        InlineResponse200 response = api.availibilityGetByProductId(id);

        // TODO: test validations
    }
    
}
